/*******************************************************************************
 * Copyright 2021, 2023 Open Text.
 *
 * The only warranties for products and services of Open Text 
 * and its affiliates and licensors ("Open Text") are as may 
 * be set forth in the express warranty statements accompanying 
 * such products and services. Nothing herein should be construed 
 * as constituting an additional warranty. Open Text shall not be 
 * liable for technical or editorial errors or omissions contained 
 * herein. The information contained herein is subject to change 
 * without notice.
 *******************************************************************************/
package com.fortify.cli.license.ncd_report.collector;

import com.fortify.cli.license.ncd_report.config.INcdReportRepoSelectorConfig;
import com.fortify.cli.license.ncd_report.descriptor.INcdReportRepositoryDescriptor;
import com.fortify.cli.license.ncd_report.generator.INcdReportBranchCommitGenerator;

/**
 * This interface is to be implemented by classes that can process
 * {@link INcdReportRepositoryDescriptor} instances generated by
 * system-specific results generators. There is currently one class
 * that implements this interface: {@link NcdReportRepositoryProcessor}.
 * 
 * @author rsenden
 *
 */
public interface INcdReportRepositoryProcessor {
    /**
     * Process the repository described by the given {@link INcdReportRepositoryDescriptor}.
     * Based on the given {@link INcdReportRepoSelectorConfig}, implementations should
     * decide whether the repository should be processed or not. If the repository should 
     * be processed, the given {@link INcdReportBranchCommitGenerator} can be invoked to 
     * generate commit data for every branch in the given repository. 
     */
    <R extends INcdReportRepositoryDescriptor> void processRepository(INcdReportRepoSelectorConfig repoSelectorConfig, R repoDescriptor, INcdReportBranchCommitGenerator<R> commitGenerator);
}