= Fortify CLI (fcli) Documentation

The fcli utility can be used to interact with various Fortify products, like Fortify on Demand (FoD), Software Security Center (SSC), ScanCentral SAST and ScanCentral DAST.

== Release Documentation

Release documentation can be accessed through the drop-down menu on the top-right, or from the sections below.

=== Releases Versions

Note that in general, maintenance is performed on the latest release version only; older versions may not receive bug fixes or compatibility updates to support the latest Fortify product releases. Fcli upgrades between minor and patch releases should be straightforward as new releases are mostly backward-compatible with older versions within the same major version range. If you are still on an older major release like v1.x, it is highly recommended to upgrade to fcli v2.x to avoid potential compatibility issues with new Fortify product releases.

++++
<ul>
{% for version in site.data.versions.release %}
   <li><a href="{{ site.baseurl }}/{{ version }}">{{ version }}</a></li>
{% endfor %}
</ul>
++++

=== Development Versions

++++
<ul>
{% for version in site.data.versions.dev %}
   <li><a href="{{ site.baseurl }}/{{ version }}">{{ version }}</a></li>
{% endfor %}
</ul>
++++

== Developer Documentation

Information useful for developers can be found in the link:./dev-info.html[developer documentation].