= Fortify CLI (fcli) Developer Information

The following sections provide information that may be useful for developers of this utility.

== Conventional Commits & Versioning

Versioning is handled automatically by https://github.com/google-github-actions/release-please-action[release-please-action] based on https://www.conventionalcommits.org/[Conventional Commits]. Every commit to the `+main+` branch should follow the Conventional Commits convention. Following are some examples; these can be combined in a single commit message (separated by empty lines), or you can have commit messages describing just a single fix or feature.

....
chore: Won't show up in changelog

ci: Change to GitHub Actions workflow; won't show up in changelog

docs: Change to documentation; won't show up in changelog

fix: Some fix (#2)

feat: New feature (#3)

feat!: Some feature that breaks backward compatibility

feat: Some feature
  BREAKING-CHANGE: No longer supports xyz
....

See the output of `+git log+` to view some sample commit messages.

`+release-please-action+` invoked from the GitHub CI workflow generates pull requests containing updated `+CHANGELOG.md+` and `+version.txt+` files based on these commit messages. Merging the pull request will
result in a new release version being published; this includes publishing the image to Docker Hub, and creating a GitHub release describing the changes.

== Technologies & Frameworks

Following is a list of the main frameworks and technologies used by fcli: 

* https://picocli.info/[picocli]: Process command line options, generate usage information, … 
* https://micronaut.io/[Micronaut]: Dependency injection, features for GraalVM native image generation 
* https://github.com/FasterXML/jackson[Jackson]: Parse and generate data in JSON and other formats 
* https://www.graalvm.org/[GraalVM]: Generate native images (native executables)

== Prerequisites & Considerations

As can be seen in the link:#_technologies_frameworks[Technologies & frameworks] section, this is no ordinary Java project. Some of these technologies and frameworks require special prerequisites, precautions and other considerations to be taken into account to prevent compilation issues and runtime errors, as described below.

=== IDE Setup

This project uses the following frameworks that may require some special setup in order to have your IDE compile this project without errors:

* Lombok: Please see https://projectlombok.org/setup/overview for more information on how to add Lombok support to your IDE
* Micronaut & picocli: These frameworks require annotation processors to be run during builds; please see your IDE documentation on how to enable annotation processing

=== Incremental Compilation

Incremental compilation (for example in IDE or when doing a `+gradle build+` without `+clean+`) may leave behind old AOT artifacts causing exceptions when trying to run `+fcli+`. This is especially the case when renaming or moving classes, which may result in exceptions like the below:

....
Message: Error loading bean [com.fortify.cli.ssc.rest.unirest.SSCUnirestRunner]: com/fortify/cli/rest/unirest/AbstractUnirestRunner
...
Caused by: java.lang.NoClassDefFoundError: com/fortify/cli/rest/unirest/AbstractUnirestRunner
...
....

In this example, the AbstractUnirestRunner class was moved to a different package, but the now obsolete AOT-generated classes were still present. So, if at any time you see unexpected exceptions, please try to do a full clean/rebuild and run `+fcli+` again.

=== Reflection

GraalVM Native Image needs to know ahead-of-time the reflectively accessed program elements; see https://www.graalvm.org/reference-manual/native-image/Reflection/[GraalVM Native Image & Reflection] for details. Micronaut allows for generating the necessary GraalVM reflection configuration using the `+@ReflectiveAccess+` annotation if necessary.

If a command runs fine on a regular JVM but not when running as a native image, then quite likely this is caused by missing reflection configuration which may be fixed by adding the `+@ReflectiveAccess+` annotation to the appropriate classes. Also see below for some reflection-related considerations specific to picocli and Jackson.

=== Picocli

Picocli and it’s annotation processor should in theory generate the necessary reflection configuration as described above. However, the annotation processor doesn’t seem to take class hierarchies into account; see https://github.com/remkop/picocli/issues/1444[GraalVM: Options from superclass not visible]. As a work-around, we can complement the picocli-generated reflection configuration by using Micronaut’s `+@ReflectiveAccess+` annotation. In general the following classes should probably be annotated with `+@ReflectiveAccess+`: 

* All classes annotated with `+@Command+` (this likely duplicates the reflection configuration generated by picocli, but doesn’t hurt) 
* All super-classes of all classes annotated with `+@Command+`, in particular if they contain any picocli annotations like `+@Mixin+`, `+@ArgGroup+`, or `+@Option+` 
* All classes used as an `+@Mixin+` or `+@ArgGroup+`, and their super-classes

The following native image runtime behavior may indicate a missing `+@ReflectiveAccess+` annotation: 

* Options and sub-commands not listed in help output, and not recognized when entered on the command line 
* Exceptions related to picocli trying to access classes, methods and fields using reflection

=== Jackson

Jackson is heavily based on reflection to perform object serialization and deserialization. All classes that need to be (de-)serialized with Jackson therefore need to be annotated with `+@ReflectiveAccess+` to allow reflection-based (de-)serialization.

Note that Micronaut provides the `+@Introspected+` annotation that should allow for reflection-free (de-)serialization. However experience learns that there are just too many differences between reflection-based
and introspection-based (de-)serialization. When running in a normal JVM these differences are often not visible as Jackson can easily fall back to reflection-based (de-)serialization. In native images, Jackson cannot fall back to reflection-based (de-)serialization unless properly configured, and even when properly configured there are still some differences in behavior.

As such, it has been decided to disable Jackson introspection-based (de-)serialization using the `+jackson.bean-introspection-module+` configuration property in `+application.yml+`. This also means that we will not be using the `+@Introspected+` annotation on classes that need to be (de-)serialized with Jackson (unless of course introspection-based access is used for non Jackson-related purposes).

== Gradle Wrapper

It is strongly recommended to build this project using the included Gradle Wrapper scripts; using other Gradle versions may result in build errors and other issues.

The Gradle build uses various helper scripts from https://github.com/fortify/shared-gradle-helpers; please refer to the documentation and comments in included scripts for more information.

== Common Commands

All commands listed below use Linux/bash notation; adjust accordingly if you are running on a different platform. All commands are to be executed from the main project directory.

* `+./gradlew tasks --all+`: List all available tasks
* Build: (plugin binary will be stored in `+build/libs+`)
** `+./gradlew clean build+`: Clean and build the project
** `+./gradlew build+`: Build the project without cleaning
** `+./gradlew dist distThirdParty+`: Build distribution zip and third-party information bundle

== Documentation

Two types of documentation are automatically being generated; the standard repository documentation like `+README.md+` and `+CONTRIBUTING.md+`, and fcli user documentation (including manual pages). The following two sections describe the generation process in more detail.

=== Repository Documentation

Most or all of the `+*.md+` and `LICENSE.txt` files located in the repository root are generated automatically. Generation of `+CHANGELOG.md+` is done by `+release-please-action+` as described in the link:#_conventional_commits_versioning[Conventional Commits & Versioning] section. Generation of the other files is done by the `+doc-resources/update-repo-docs.sh+` scripts, based on the templates provided in https://github.com/fortify/shared-doc-resources, combined with the repo-specific MarkDown files in the repository `+doc-resources+` directory. For more information about this generation process, please see https://github.com/fortify/shared-doc-resources/blob/main/USAGE.md.

=== User Documentation

User documentation is generated automatically from the following three locations:

* AsciiDoc located in the repository `+doc-resources/asciidoc/gh-pages+` directory
** Published to the root directory of the GitHub Pages site
* AsciiDoc located in the repository `+doc-resources/asciidoc/versioned+` directory
** Published to a version-specific directory on the GitHub Pages site
** Published to docs-html.zip in release assets
* Manual pages generated from the fcli code
** Published to a version-specific directory on the GitHub Pages site
** Published to docs-html.zip in release assets
** Published to docs-manpage.zip in release assets

The Gradle build includes various tasks for generating this documentation, following are the main tasks:

* `+generateManpageAsciiDoc+`: Generate man-page style AsciiDoc documentation from fcli code
* `+asciiDoctorManPage+`: Convert man-page style AsciiDoc to Linux man-page format
* `+asciiDoctorHtml+`: Convert both man-page style AsciiDoc and versioned user documentation to offline HTML format
* `+asciidoctorJekyll+`: Convert both man-page style AsciiDoc and versioned user documentation to Jekyll HTML format for publishing on the GitHub Pages site
* `+asciidoctorGHPages+`: Convert AsciiDoc files from `+doc-resources/asciidoc/gh-pages+` to Jekyll HTML format for publishing on the GitHub Pages site
* `+distDocs+`: Calls of the tasks above and packages the output from these tasks into separate `+docs-*.zip+` files in the `+build/dist+` directory

The GitHub Actions workflow defined in `+.github/workflows/ci.yml+` is responsible for publishing the documentation:

* The `+build+` job builds the documentation artifacts and archives them as artifacts
* The `+release+` job publishes `+docs-html.zip+` and `+docs-manpage.zip+` to the release artifacts (when building a release or development version)
* The `+publishPages+` job published the output of the `+asciidoctorJekyll+` and `+asciidoctorGHPages+` to the appropriate directories on the GitHub Pages site, and updates the version index in the Jekyll `+_data+` directory (when building a release or development version)

All HTML-formatted documentation described above is generated using the `+doc-resources/templates/html5/document.html.erb+` template. This template is based on the link:https://github.com/asciidoctor/asciidoctor-backends/blob/master/erb/html5/document.html.erb[official AsciiDoctor template] with various modifications. Based on the attributes provided in the relevant Gradle tasks:

* For Jekyll output:
** Add Jekyll front matter
** Add a Jekyll include to include additional content in the HTML `+<head>+` section; mostly used for applying stylesheets
** Add a Jekyll include to include the site-wide banner and (version) navigation bar
* For offline HTML output:
** Add hardcoded custom styling
** Add hardcoded banner and version bar

The offline HTML documentation is supposed to be self-contained, i.e., users can open any HTML file from `+docs-html.zip+` without extracting the full contents, and the page will render correctly. Of course, links to other documentation files will not work unless the full zip-file is extracted.

For now, the hardcoded banner and navigation bar in the offline documentation is similar to the banner included by Jekyll. However:

* Stylesheets and images are linked rather than being included in the HTML page, allowing for better browser cache utilization
* The navigation bar in the offline documentation contains just a static version number, whereas the navigation bar in the online documentation allows for navigating to different versions
* We can potentially add more advanced (navigation) functionalities in the online documentation
* We can easily update the banner for the online documentation to have a new layout/styling, for example to apply OpenText styling; this will be automatically applied to all existing online documentation pages

Usually it shouldn't be necessary to update the documentation contents for existing release versions. However, if necessary, and assuming the build.gradle file is compatible with older versions, potentially a command like the following can be used to regenerate the documentation for the given versions:

....
for v in 1.0.0 1.0.1 1.0.2 1.0.3 1.0.4 1.0.5 1.1.0 1.2.0 1.2.1 1.2.2; do (git restore . && git clean -fd && git checkout v$v && cp -r ../fcli-fork/doc-resources ../fcli-fork/build.gradle . && ./gradlew clean distDocs -Pversion=$v && mkdir -p ~/Downloads/fcli-docs/$v && cp build/dist/docs-html.zip ~/Downloads/fcli-docs/$v && cd ../fcli-pages/v$v && echo $pwd && rm -rf * && unzip ../../fcli/build/dist/docs-jekyll.zip && cd - && git restore . && git clean -fd); done
....

This command iterates over the given version numbers, regenerates the documentation for each version (using latest `+build.gradle+` and `+doc-resources+`), copies the `docs-html.zip` to a separate directory for later upload to the corresponding release assets, and updates the GitHub Pages site, based on the following assumptions:

* Current directory is a clone of the fcli repository
* `+../fcli-fork+` would contain the latest version of `+doc-resources+` and `+build.gradle+`
* `+../fcli-pages+` would be a clone of the fcli repository with the gh-pages branch checked out


