---
name: ${templateName}           # Required: Report template name
description: Test Description   # Optional: Report template description
type: ISSUE                     # Required: ISSUE, PROJECT or PORTFOLIO
parameters:
- name: Param1                  # Required: Report parameter name
  description: ParamDescription # Optional: Report parameter description
  identifier: param1            # Required: ID/name of the report parameter in the BIRT template.
  type: SINGLE_SELECT_DEFAULT   # Required: BOOLEAN, MULTI_PROJECT, PROJECT_ATTRIBUTE, SINGLE_PROJECT, SINGLE_SELECT_DEFAULT, STRING, or DATE
  paramOrder: 0                 # Optional: Report parameter ordering value
  reportParameterOptions:       # Required for parameter type "SINGLE_SELECT_DEFAULT", not allowed for other parameter types
  - defaultValue: true          # Required: Boolean indicating whether this is the default parameter option
    description: Opt1Desc        # Optional: Report parameter option description
    displayValue: Option 1      # Required: Report parameter display value as shown in SSC UI
    reportValue: 1              # Required: The value to be passed to the BIRT template
  - defaultValue: false         # See above
    description: Opt1Desc       # See above
    displayValue: Option 2      # See above
    reportValue: 2              # See above
- name: Param2                  # Repeated section above for additional report parameter but different type 
  paramOrder: 1
  description: Param2Description
  identifier: param2
  type: STRING
