/*
 * Copyright 2021-2026 Open Text.
 *
 * The only warranties for products and services of Open Text
 * and its affiliates and licensors ("Open Text") are as may
 * be set forth in the express warranty statements accompanying
 * such products and services. Nothing herein should be construed
 * as constituting an additional warranty. Open Text shall not be
 * liable for technical or editorial errors or omissions contained
 * herein. The information contained herein is subject to change
 * without notice.
 */
package com.fortify.cli.license.ncd_report.reader;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.FileSystem;
import java.nio.file.FileSystems;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import java.util.stream.Stream;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.MappingIterator;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.fasterxml.jackson.dataformat.csv.CsvMapper;
import com.fasterxml.jackson.dataformat.csv.CsvSchema;
import com.fasterxml.jackson.dataformat.yaml.YAMLFactory;
import com.fasterxml.jackson.datatype.jdk8.Jdk8Module;
import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule;
import com.fortify.cli.common.exception.FcliSimpleException;
import com.fortify.cli.common.exception.FcliTechnicalException;
import com.fortify.cli.license.ncd_report.config.NcdReportConfig;
import com.fortify.cli.license.ncd_report.config.NcdReportContributorConfig;
import com.fortify.cli.license.ncd_report.helper.NcdReportContributorHelper;

import lombok.Getter;

/**
 * Read helper for NCD reports generated by the {@code ncd-report create}
 * command. Supports both report directory and report zip input formats.
 */
public final class NcdReportReader implements AutoCloseable {
    private static final CsvMapper CSV_MAPPER = new CsvMapper();
    private static final ObjectMapper YAML_MAPPER = createYamlMapper();

    @Getter private final Path reportPath;
    @Getter private final boolean directoryReport;
    private final FileSystem fileSystem;

    public NcdReportReader(Path reportPath) {
        this.reportPath = reportPath.toAbsolutePath();
        if ( !Files.exists(this.reportPath) ) {
            throw new FcliSimpleException("Report path not found: %s", this.reportPath);
        }
        this.directoryReport = Files.isDirectory(this.reportPath);
        this.fileSystem = directoryReport ? null : openZipFileSystem(this.reportPath);
    }

    public Path entryPath(String entryName) {
        if ( directoryReport ) {
            return reportPath.resolve(entryName).normalize();
        }
        var normalizedEntry = entryName.replace('\\', '/');
        return fileSystem.getPath(normalizedEntry);
    }

    public BufferedReader bufferedReader(String entryName) {
        var entryPath = entryPath(entryName);
        if ( !Files.exists(entryPath) ) {
            throw new FcliSimpleException("Report entry not found: %s in %s", entryName, reportPath);
        }
        try {
            return Files.newBufferedReader(entryPath);
        } catch ( IOException e ) {
            throw new FcliTechnicalException(String.format("Error opening report entry %s in %s", entryName, reportPath), e);
        }
    }

    public NcdReportConfig readConfig() {
        var configPath = entryPath("report-config.yaml");
        if ( !Files.exists(configPath) ) {
            throw new FcliSimpleException("Report entry not found: report-config.yaml in %s", reportPath);
        }
        try ( var is = Files.newInputStream(configPath) ) {
            return YAML_MAPPER.readValue(is, NcdReportConfig.class);
        } catch ( Exception e ) {
            throw new FcliTechnicalException(String.format("Error reading report config from %s", reportPath), e);
        }
    }

    public NcdReportContributorConfig readContributorConfig() {
        var config = readConfig();
        return config.getContributor().orElseGet(NcdReportContributorConfig::new);
    }

    public ObjectNode readSummary() {
        var summaryPath = entryPath("summary.txt");
        if ( !Files.exists(summaryPath) ) {
            throw new FcliSimpleException("Report entry not found: summary.txt in %s", reportPath);
        }
        try ( InputStream is = Files.newInputStream(summaryPath) ) {
            return YAML_MAPPER.readValue(is, ObjectNode.class);
        } catch ( Exception e ) {
            throw new FcliTechnicalException(String.format("Error reading summary.txt from %s", reportPath), e);
        }
    }

    public List<Map<String, String>> readContributors() {
        try ( var csvReader = bufferedReader("contributors.csv") ) {
            var schema = CsvSchema.emptySchema().withHeader();
            MappingIterator<Map<String, String>> iterator = CSV_MAPPER
                    .readerFor(new TypeReference<Map<String, String>>() {})
                    .with(schema)
                    .readValues(csvReader);
            var result = new ArrayList<Map<String, String>>();
            while ( iterator.hasNext() ) {
                var row = iterator.next();
                NcdReportContributorHelper.normalizeContributorRow(row);
                result.add(row);
            }
            return result;
        } catch ( Exception e ) {
            throw new FcliSimpleException("Error reading contributors.csv from %s:\n\tMessage: %s", reportPath, e.getMessage());
        }
    }

    public List<String> listFileEntries() {
        try ( var paths = fileEntryPathStream() ) {
            return paths
                .filter(Files::isRegularFile)
                .map(this::toEntryName)
                .sorted()
                .collect(Collectors.toList());
        } catch ( IOException e ) {
            throw new FcliTechnicalException(String.format("Error listing report entries for %s", reportPath), e);
        }
    }

    @Override
    public void close() {
        if ( fileSystem != null ) {
            try {
                fileSystem.close();
            } catch ( IOException e ) {
                throw new FcliTechnicalException(String.format("Error closing report file system for %s", reportPath), e);
            }
        }
    }

    private static FileSystem openZipFileSystem(Path zipPath) {
        try {
            return FileSystems.newFileSystem(zipPath);
        } catch ( Exception e ) {
            throw new FcliSimpleException("Invalid report zip file: %s", zipPath);
        }
    }

    private static ObjectMapper createYamlMapper() {
        var mapper = new ObjectMapper(new YAMLFactory());
        mapper.registerModule(new Jdk8Module());
        mapper.registerModule(new JavaTimeModule());
        return mapper;
    }

    private Stream<Path> fileEntryPathStream() throws IOException {
        return directoryReport
                ? Files.walk(reportPath)
                : Files.walk(fileSystem.getPath("/"));
    }

    private String toEntryName(Path filePath) {
        if ( directoryReport ) {
            return reportPath.relativize(filePath).toString().replace('\\', '/');
        }
        return filePath.toString().replace('\\', '/').replaceFirst("^/+", "");
    }
}
