/*
 * Copyright 2021-2026 Open Text.
 *
 * The only warranties for products and services of Open Text
 * and its affiliates and licensors ("Open Text") are as may
 * be set forth in the express warranty statements accompanying
 * such products and services. Nothing herein should be construed
 * as constituting an additional warranty. Open Text shall not be
 * liable for technical or editorial errors or omissions contained
 * herein. The information contained herein is subject to change
 * without notice.
 */
package com.fortify.cli.common.util;

import java.io.File;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.atomic.AtomicReference;
import java.util.stream.Stream;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.formkiq.graalvm.annotations.Reflectable;
import com.fortify.cli.common.spel.fn.descriptor.annotation.SpelFunction;
import com.fortify.cli.common.spel.fn.descriptor.annotation.SpelFunction.SpelFunctionCategory;
import com.fortify.cli.common.spel.fn.descriptor.annotation.SpelFunctionParam;
import com.fortify.cli.common.spel.fn.descriptor.annotation.SpelFunctions;

import lombok.Builder;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.SneakyThrows;

/**
 * <p>Due to the way that Fortify packages and scans code, source file paths returned by FoD and SSC
 * may not exactly match original source file paths. In some cases, a leading path may be added
 * by Fortify, like /scancentral12345678/work/..., whereas in other cases, leading paths may be
 * stripped, like removing src/main/java from a path like src/main/java/my/pkg/Class.java</p>
 * 
 * <p>This may lead to user confusion, and may cause issues when importing reports generated by
 * fcli actions like gitlab-sast-report or github-sast-report into the respective 3rd-party systems, 
 * as these systems will then be unable to match the file path on which an issue is being reported
 * against an actual repository path.</p>
 * 
 * <p>To work around these issues, this class attempts to map Fortify-provided issue source file 
 * paths against local file system paths relative to a given workspace/repository root directory, 
 * using partial path matching to find the longest matching suffix. The {@link #workspacePath} should 
 * be set to the workspace/repository root directory for proper resolution.</p>
 * 
 * <p><strong>Example:</strong> If the workspace is {@code /home/runner/workspace} containing 
 * {@code sources/my-pkg/sub-path/test.js}, and Fortify scanned only {@code sources/my-pkg}, 
 * Fortify will report {@code sub-path/test.js}. This resolver will match it against the indexed 
 * {@code sources/my-pkg/sub-path/test.js} and return the full workspace-relative path.</p>
 *  
 * @author Ruud Senden
 */
// TODO Also see TODO comments in IssueSourceFileResolverTest
// TODO How to handle absolute paths? Always return as-is (or null if not existing and OnNoMatch.NULL)? Or try to resolve against workspacePath?
// TODO How to handle drive letters (with either absolute or relative path)?
// NOTE: Any changes to this class will result in action schema changes, so action schema version should be bumped when modifying this class, and the changelog should include a note about potential impact on users' custom actions that use this class.
@Builder @Reflectable @SpelFunctions
public class IssueSourceFileResolver {
    private static final Logger LOG = LoggerFactory.getLogger(IssueSourceFileResolver.class);
    /** Workspace/repository root directory path for indexing and resolving file paths */
    @Getter private final Path workspacePath;
    /** Optional source directory that was scanned - used for prioritizing matches when multiple files have the same name */
    @Getter private final Path sourcePath;
    @Builder.Default private final OnNoMatch onNoMatch = OnNoMatch.ORIGINAL;
    @Builder.Default private final FileSeparator separatorOnReturn = FileSeparator.LINUX;
    private final AtomicReference<SourceFileIndex> indexReference = new AtomicReference<>();
    
    @SpelFunction(cat=SpelFunctionCategory.fortify,
            desc="Resolves Fortify-reported issue path to workspace-relative path string using configured file separator",
            returns="Workspace-relative path string, or null/original based on onNoMatch setting")
    public final String resolve(
            @SpelFunctionParam(name="issuePath", desc="Fortify-reported source file path") String issuePath) {
        return FileUtils.pathToString(resolve(Path.of(issuePath)), separatorOnReturn.getSeparatorChar());
    }
    
    @SpelFunction(cat=SpelFunctionCategory.fortify,
            desc="Validates that resolved path exists as a regular file with valid line number (>0)",
            returns="true if workspacePath is null (no validation), or if resolved file exists and lineNumber > 0")
    public final boolean exists(
            @SpelFunctionParam(name="issuePath", desc="Fortify-reported source file path") String issuePath,
            @SpelFunctionParam(name="lineNumber", desc="Line number to validate (1-based)") int lineNumber) {
        if ( workspacePath == null ) {
            return true; // No validation possible without source path
        }
        if ( lineNumber <= 0 ) {
            return false; // Invalid line number
        }
        var resolvedPath = resolve(Path.of(issuePath));
        if ( resolvedPath == null ) {
            return false;
        }
        var fullPath = workspacePath.resolve(resolvedPath);
        return Files.exists(fullPath) && Files.isRegularFile(fullPath);
        // Note: We don't validate the actual line count as it would require reading the entire file,
        // which could be expensive for large codebases. GitHub will handle non-existent lines gracefully.
    }

    /**
     * Path-based variant of {@link #resolve(String)}. Not exposed as SpEL function to avoid
     * name collision; use the String-based variant in actions.
     */
    private final Path resolve(Path issuePath) {
        var result = indexReference.updateAndGet(this::createIndexIfNull).resolve(issuePath);
        if ( result!=null && LOG.isTraceEnabled() ) { LOG.trace("Resolved issue path {} to source path {}", issuePath, result); }
        if ( result==null && onNoMatch==OnNoMatch.ORIGINAL ) {
            result = issuePath;
        }
        return result;
    }
    
    private final SourceFileIndex createIndexIfNull(SourceFileIndex index) {
        if ( index==null ) {
            index = new SourceFileIndex(workspacePath, sourcePath);
        }
        return index;
    }
    
    public static enum OnNoMatch {
        NULL, ORIGINAL
    }
    
    @RequiredArgsConstructor
    public static enum FileSeparator {
        LINUX('/'), WINDOWS('\\'), PLATFORM(File.separatorChar);
        
        @Getter private final char separatorChar;
    }
    
    private static final class SourceFileIndex {
        /** Full relative paths only, like src/main/java/com/fortify/X.java.
         * Values are lists to handle multiple files with the same name (e.g., index.js in multiple directories) */
        private final Map<String,java.util.List<Path>> fullRelativePathsIndex;
        /** Full and partial relative paths, like src/main/java/com/fortify/X.java, com/fortify/X.java, X.java.
         * Values are lists to handle multiple files with the same name (e.g., index.js in multiple directories) */ 
        private final Map<String,java.util.List<Path>> fullAndPartialRelativePathsIndex;
        /** Optional source path (relative to workspace) for prioritizing matches */
        private final Path sourcePathRelative;
        
        private SourceFileIndex(Path workspacePath, Path sourcePath) {
            this.sourcePathRelative = computeSourcePathRelative(workspacePath, sourcePath);
            var fullPaths = createFullRelativePathsIndex(workspacePath);
            this.fullRelativePathsIndex = fullPaths;
            this.fullAndPartialRelativePathsIndex = createFullAndPartialRelativePathsIndex(fullPaths.values());
        }
        
        private static Path computeSourcePathRelative(Path workspacePath, Path sourcePath) {
            if ( workspacePath==null || sourcePath==null ) { return null; }
            
            var normalizedWorkspace = workspacePath.normalize().toAbsolutePath();
            var absoluteSource = sourcePath.isAbsolute() 
                ? sourcePath.normalize() 
                : normalizedWorkspace.resolve(sourcePath).normalize();
            
            if ( absoluteSource.startsWith(normalizedWorkspace) ) {
                return normalizedWorkspace.relativize(absoluteSource);
            } else {
                if ( LOG.isWarnEnabled() ) {
                    LOG.warn("sourceDir {} is not under workspaceDir {}, will not prioritize matches", absoluteSource, normalizedWorkspace);
                }
                return null;
            }
        }
        
        /**
         * <p>This method first tries to match the given path against {@link #fullAndPartialRelativePathsIndex}, which, given a 
         * source path <code>src/main/java/com/fortify/X.java</code>, will match each of the following input paths:
         * <code>X.java</code>, <code>com/fortify/X.java</code>, and <code>src/main/java/com/fortify/X.java</code>. This handles 
         * situations where Fortify strips leading directories.</p>
         * 
         * <p>If no match is found in {@link #fullAndPartialRelativePathsIndex}, this method will then attempt to match any of 
         * the sub-paths in the given path against {@link #fullRelativePathsIndex}, which, given a source path
         * <code>src/main/java/com/fortify/X.java</code>, will match an input path like 
         * <code>any/leading/dir/src/main/java/com/fortify/X.java</code>, but not <code>any/leading/dir/com/fortify/X.java</code>.</p>
         * 
         * <p>When multiple files match (e.g., both <code>src/index.js</code> and <code>src/node_modules/pkg/index.js</code>),
         * this method prioritizes matches under {@link #sourcePath} if provided, then selects the shortest path.</p>
         */
        protected final Path resolve(Path path) {
            if ( path==null ) { return null; }
            var normalizedPath = path.normalize();
            var candidates = fullAndPartialRelativePathsIndex.get(pathToString(normalizedPath));
            return candidates!=null ? selectBestCandidate(candidates) : resolveByStrippingLeadingDirs(normalizedPath);
        }

        /**
         * Select the best candidate from a list of matching paths.
         * Priority: 1) paths under sourcePath, 2) shortest path (fewest components)
         */
        private Path selectBestCandidate(java.util.List<Path> candidates) {
            if ( candidates==null || candidates.isEmpty() ) { return null; }
            if ( candidates.size()==1 ) { return candidates.get(0); }
            
            // Try to prefer paths under sourcePath if provided
            if ( sourcePathRelative!=null ) {
                var inSourceDir = candidates.stream()
                    .filter(p -> p.startsWith(sourcePathRelative))
                    .toList();
                if ( !inSourceDir.isEmpty() ) {
                    candidates = inSourceDir;
                    if ( LOG.isDebugEnabled() && candidates.size() > 1 ) {
                        LOG.debug("Multiple matches found under sourceDir {}: {}", sourcePathRelative, candidates);
                    }
                }
            }
            
            // Among remaining candidates, prefer shortest path
            var result = candidates.stream()
                .min(java.util.Comparator.comparingInt(Path::getNameCount))
                .orElse(candidates.get(0));
            
            if ( LOG.isDebugEnabled() && candidates.size() > 1 ) {
                LOG.debug("Selected {} from candidates: {}", result, candidates);
            }
            
            return result;
        }

        private Path resolveByStrippingLeadingDirs(Path normalizedPath) {
            var nameCount = normalizedPath.getNameCount();
            if ( nameCount <= 1 ) { return null; }
            
            var subPath = normalizedPath.subpath(1, nameCount);
            var candidates = fullRelativePathsIndex.get(pathToString(subPath));
            return candidates!=null ? selectBestCandidate(candidates) : resolveByStrippingLeadingDirs(subPath);
        }

        @SneakyThrows
        private static final Map<String, java.util.List<Path>> createFullRelativePathsIndex(Path workspacePath) {
            var result = new HashMap<String, java.util.List<Path>>();
            if ( workspacePath!=null && Files.isDirectory(workspacePath) ) {
                var normalizedWorkspacePath = workspacePath.normalize();
                try (Stream<Path> stream = Files.walk(normalizedWorkspacePath)) {
                    stream.filter(Files::isRegularFile)
                        .forEach(p->{
                            var fullRelativePath = normalizedWorkspacePath.relativize(p.normalize());
                            if ( LOG.isTraceEnabled() ) { LOG.trace("Adding source path {} to index", fullRelativePath); }
                            var key = pathToString(fullRelativePath);
                            result.computeIfAbsent(key, k -> new java.util.ArrayList<>()).add(fullRelativePath);
                        });
                }
            }
            return result;
        }
        
        private static final Map<String, java.util.List<Path>> createFullAndPartialRelativePathsIndex(java.util.Collection<java.util.List<Path>> fullRelativePaths) {
            var result = new HashMap<String, java.util.List<Path>>();
            fullRelativePaths.forEach(paths -> 
                paths.forEach(fullRelativePath -> 
                    addPathToFullAndPartialRelativePathsIndex(result, fullRelativePath, fullRelativePath)
                )
            );
            return result;
        }
        
        private static final void addPathToFullAndPartialRelativePathsIndex(Map<String, java.util.List<Path>> index, Path fullRelativePath, Path partialRelativePath) {
            var key = pathToString(partialRelativePath);
            index.computeIfAbsent(key, k -> new java.util.ArrayList<>()).add(fullRelativePath);
            var nameCount = partialRelativePath.getNameCount(); 
            if ( nameCount > 1 ) {
                addPathToFullAndPartialRelativePathsIndex(index, fullRelativePath, partialRelativePath.subpath(1, nameCount));
            }
        }
        
        private static final String pathToString(Path normalizedPath) {
            return FileUtils.pathToString(normalizedPath, '/');
        }
    }
}
