/**
 * Copyright 2023 Open Text.
 *
 * The only warranties for products and services of Open Text 
 * and its affiliates and licensors ("Open Text") are as may 
 * be set forth in the express warranty statements accompanying 
 * such products and services. Nothing herein should be construed 
 * as constituting an additional warranty. Open Text shall not be 
 * liable for technical or editorial errors or omissions contained 
 * herein. The information contained herein is subject to change 
 * without notice.
 */
package com.fortify.cli.common.util;

import java.io.File;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.atomic.AtomicReference;
import java.util.stream.Stream;

import com.formkiq.graalvm.annotations.Reflectable;

import lombok.Builder;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.SneakyThrows;

/**
 * <p>Due to the way that Fortify packages and scans code, source file paths returned by FoD and SSC
 * may not exactly match original source file paths. In some cases, a leading path may be added
 * by Fortify, like /scancentral12345678/work/..., whereas in other cases, leading paths may be
 * stripped, like removing src/main/java from a path like src/main/java/my/pkg/Class.java</p>
 * 
 * <p>This may lead to user confusion, and may cause issues when importing reports generated by
 * fcli actions like gitlab-sast-report or github-sast-report into the respective 3rd-party systems, 
 * as these systems will then be unable to match the file path on which an issue is being reported
 * against an actual repository path.</p>
 * 
 * <p>To work around these issues, this class attempts to map Fortify-provided issue source file 
 * paths against local file system paths relative to a given source code directory, basically 
 * finding the longest matching path suffix.</p>
 *  
 * @author Ruud Senden
 */
// TODO Also see TODO comments in IssueFilePathFinderTest
// TODO How to handle absolute paths? Always return as-is (or null if not existing and OnNoMatch.NULL)? Or try to resolve against repoPath?
// TODO How to handle drive letters (with either absolute or relative path)?
@Builder @Reflectable
public class IssueFilePathFinder {
    private final Path repoPath;
    @Builder.Default private final OnNoMatch onNoMatch = OnNoMatch.ORIGINAL;
    @Builder.Default private final FileSeparator separatorOnReturn = FileSeparator.LINUX;
    private final AtomicReference<RepoFileIndex> indexReference = new AtomicReference<>();
    
    @Reflectable
    // We provide convenience methods for use in fcli actions, as these can't reference enum constants.
    public static class IssueFilePathFinderBuilder {
        public final IssueFilePathFinderBuilder nullOnNoMatch() {
            return onNoMatch(OnNoMatch.NULL);
        }
        public final IssueFilePathFinderBuilder originalOnNoMatch() {
            return onNoMatch(OnNoMatch.ORIGINAL);
        }
        public final IssueFilePathFinderBuilder linuxSeparatorOnReturn() {
            return separatorOnReturn(FileSeparator.LINUX);
        }
        public final IssueFilePathFinderBuilder windowsSeparatorOnReturn() {
            return separatorOnReturn(FileSeparator.WINDOWS);
        }
        public final IssueFilePathFinderBuilder platformSeparatorOnReturn() {
            return separatorOnReturn(FileSeparator.PLATFORM);
        }
    }
    
    /**
     * Find the given {@link Path} in the configured repository path. Based on the Fortify behavior
     * described in the class description, if the configured repository path contains a single file 
     * <code>src/main/java/com/fortify/X.java</code>, this method will return a relative {@link Path} 
     * representing <code>src/main/java/com/fortify/X.java</code> for each of the following input paths:
     * <ul>
     *  <li><code>scancentral123/work/src/main/java/com/fortify/X.java</code></li>
     *  <li><code>any/leading/dir/src/main/java/com/fortify/X.java</code></li>
     *  <li><code>src/main/java/com/fortify/X.java</code></li>
     *  <li><code>main/java/com/fortify/X.java</code></li>
     *  <li><code>java/com/fortify/X.java</code></li>
     *  <li><code>com/fortify/X.java</code></li>
     *  <li><code>fortify/X.java</code></li>
     *  <li><code>X.java</code></li>
     * </ul>
     * Any other input path will be considered a non-matching path, in which case either the given 
     * path or <code>null</code> will be returned, based on the configured {@link OnNoMatch} setting.
     * In particular, note that if the given path includes a leading directory, it will only match
     * if any of its sub-paths match the full relative repository path. With the example above, this
     * means that <code>scancentral123/work/com/fortify/X.java</code> will be considered non-matching,
     * as it lacks the <code>src/main/java</code> path.
     */
    public final Path find(Path issuePath) {
        var result = indexReference.updateAndGet(this::createIndexIfNull).find(issuePath);
        if ( result==null && onNoMatch==OnNoMatch.ORIGINAL ) {
            result = issuePath;
        }
        return result;
    }
    
    /**
     * This is the {@link String}-based variant of {@link #find(Path)}:
     * <ol>
     *  <li>Convert the given {@link String} into a {@link Path} instance</li>
     *  <li>Call the {@link #find(Path)} method to find this path in the configured repository path</li>
     *  <li>Convert the {@link Path} instance returned by {@link #find(Path)} into a {@link String},
     *      using the configured {@link #separatorOnReturn} file separator.</li>
     * </ol>
     */
    public final String find(String issuePath) {
        return FileUtils.pathToString(find(Path.of(issuePath)), separatorOnReturn.getSeparatorChar());
    }
    
    private final RepoFileIndex createIndexIfNull(RepoFileIndex index) {
        if ( index==null ) {
            index = new RepoFileIndex(repoPath);
        }
        return index;
    }
    
    public static enum OnNoMatch {
        NULL, ORIGINAL
    }
    
    @RequiredArgsConstructor
    public static enum FileSeparator {
        LINUX('/'), WINDOWS('\\'), PLATFORM(File.separatorChar);
        
        @Getter private final char separatorChar;
    }
    
    private static final class RepoFileIndex {
        /** Full relative paths, like src/main/java/com/fortify/X.java */
        private final Map<String,Path> fullRelativePathsIndex;
        /** Full and partial relative paths, like src/main/java/com/fortify/X.java, com/fortify/X.java, X.java */ 
        private final Map<String,Path> fullAndPartialRelativePathsIndex;
        
        private RepoFileIndex(Path repoPath) {
            this.fullRelativePathsIndex = createFullRelativePathsIndex(repoPath);
            this.fullAndPartialRelativePathsIndex = createFullAndPartialRelativePathsIndex(fullRelativePathsIndex.values());
        }
        
        /**
         * <p>This method first tries to match the given path against {@link #fullAndPartialRelativePathsIndex}, which, given a 
         * repository path <code>src/main/java/com/fortify/X.java</code>, will match each of the following input paths:
         * <code>X.java</code>, <code>com/fortify/X.java</code>, and <code>src/main/java/com/fortify/X.java</code>. This handles 
         * situations where Fortify strips leading directories.</p>
         * 
         * <p>If no match is found in {@link #fullAndPartialRelativePathsIndex}, this method will then attempt to match any of 
         * the sub-paths in the given path against {@link #fullRelativePathsIndex}, which, given a repository path
         * <code>src/main/java/com/fortify/X.java</code>, will match an input path like 
         * <code>any/leading/dir/src/main/java/com/fortify/X.java</code>, but not <code>any/leading/dir/com/fortify/X.java</code>.</p> 
         */
        protected final Path find(Path path) {
            var normalizedPath = path.normalize();
            var result = fullAndPartialRelativePathsIndex.get(pathToString(normalizedPath));
            return result!=null ? result : findSubPathInFullRelativePathsIndex(path);
        }

        private Path findSubPathInFullRelativePathsIndex(Path normalizedPath) {
            var result = fullRelativePathsIndex.get(pathToString(normalizedPath));
            if ( result==null ) {
                var nameCount = normalizedPath.getNameCount();
                if ( nameCount > 1 ) {
                    return findSubPathInFullRelativePathsIndex(normalizedPath.subpath(1, nameCount));
                }
            }
            return result;
        }

        @SneakyThrows
        private static final Map<String, Path> createFullRelativePathsIndex(Path repoPath) {
            var result = new HashMap<String, Path>();
            if ( repoPath!=null && Files.isDirectory(repoPath) ) {
                var normalizedRepoPath = repoPath.normalize();
                try (Stream<Path> stream = Files.walk(normalizedRepoPath)) {
                    stream.filter(Files::isRegularFile)
                          .forEach(p->addPathToFullRelativePathsIndex(result, normalizedRepoPath.relativize(p.normalize())));
                }
            }
            return result;
        }

        private static final void addPathToFullRelativePathsIndex(Map<String, Path> result, Path fullRelativePath) {
            result.put(pathToString(fullRelativePath), fullRelativePath);
        }
        
        private static final Map<String, Path> createFullAndPartialRelativePathsIndex(Collection<Path> fullRelativePaths) {
            var result = new HashMap<String, Path>();
            fullRelativePaths.forEach(p->addPathToFullAndPartialRelativePathsIndex(result, p, p));
            return result;
        }
        
        private static final void addPathToFullAndPartialRelativePathsIndex(Map<String, Path> index, Path fullRelativePath, Path partialRelativePath) {
            index.put(pathToString(partialRelativePath), fullRelativePath);
            var nameCount = partialRelativePath.getNameCount(); 
            if ( nameCount > 1 ) {
                addPathToFullAndPartialRelativePathsIndex(index, fullRelativePath, partialRelativePath.subpath(1, nameCount));
            }
        }
        
        private static final String pathToString(Path normalizedPath) {
            return FileUtils.pathToString(normalizedPath, '/');
        }
    }
}
