lineCommentSymbols:
  JAVA: "//"
  JSP: "<%--"
  TLD: "<!--"
  JSPX: "<!--"
  SCALA: "//"
  TYPESCRIPT: "//"
  VUE: "//"
  PHP: "//"
  PYTHON: "#"
  HTML: "<!--"
  SQL: "--"
  PLSQL: "--"
  XML: "<!--"
  HOCON: "#"
  YAML: "#"
  FLIGHT: "#"
  JAVA_PROPERTIES: "#"
  CFML: "//"
  MSIL: "//"
  COBOL: "*"
  CSHARP: "//"
  VB: "'"
  ASPNET: "<%--"
  ASP: "'"
  VBSCRIPT: "'"
  VB6: "'"
  APEX: "//"
  APEX_OBJECT: "//"
  APEX_TRIGGER: "//"
  ABAP: "*"
  ACTIONSCRIPT: "//"
  MXML: "<!--"
  RUBY: "#"
  RUBY_ERB: "#"
  SWIFT: "//"
  VISUAL_FORCE: "<!--"
  GO: "//"
  KOTLIN: "//"
  DART: "//"
  DOCKERFILE: "#"
  SOLANA: "//"
  BICEP: "//"
  ARM: "//"
  TSQL: "--"
  C: "//"
  C++: "//"
  OBJECTIVE_C: "//"
  KEY_FILE: "#"
  MARKDOWN: "<!--"