/**
 * Copyright 2023 Open Text.
 *
 * The only warranties for products and services of Open Text 
 * and its affiliates and licensors ("Open Text") are as may 
 * be set forth in the express warranty statements accompanying 
 * such products and services. Nothing herein should be construed 
 * as constituting an additional warranty. Open Text shall not be 
 * liable for technical or editorial errors or omissions contained 
 * herein. The information contained herein is subject to change 
 * without notice.
 */
package com.fortify.cli.common.action.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyDescription;
import com.formkiq.graalvm.annotations.Reflectable;
import com.fortify.cli.common.spring.expression.wrapper.TemplateExpression;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

/**
 * This class describes a forEach element, allowing iteration over the output of
 * a given input.
 */
@Reflectable @NoArgsConstructor
@Data @EqualsAndHashCode(callSuper = true)
public final class ActionStepFcli extends AbstractActionStep {
    @JsonPropertyDescription("Required: Arguments to pass to the fcli command, for example 'ssc appversion list --embed=attrValuesByName'.")
    @JsonProperty(required = true) private TemplateExpression args;
    
    @JsonPropertyDescription("Optional: Name to assign to the outcome of this fcli invocation. Can be referenced in subsequent steps using ${<name>}.")
    @JsonProperty(required = false) private String name;
    
    @JsonPropertyDescription("Optional: Steps to be executed for each individual record generated by the given fcli invocation.")
    @JsonProperty(value = "forEach", required = false) private ActionStepFcli.ActionStepFcliForEachDescriptor forEach;
    
    /**
     * This method is invoked by the {@link ActionStep#postLoad()}
     * method. It checks that required properties are set, then calls the postLoad() method for
     * each sub-step.
     */
    public final void postLoad(Action action) {
        Action.checkNotNull("fcli args", args, this);
    }
    
    /**
     * This class describes an fcli forEach element, allowing iteration over the output of
     * the fcli command. 
     */
    @Reflectable @NoArgsConstructor
    @Data @EqualsAndHashCode(callSuper = true)
    public static final class ActionStepFcliForEachDescriptor extends AbstractActionStepForEach {
        protected final void _postLoad(Action action) {}
    }
}