package com.fortify.cli.util.ncd_report.collector;

import com.fortify.cli.util.ncd_report.descriptor.NcdReportBranchCommitDescriptor;

/**
 * This interface is to be implemented by classes that can collect
 * {@link NcdReportBranchCommitDescriptor} instances generated by
 * system-specific results generators. There is currently one class
 * that implements this interface: {@link NcdReportRepositoryBranchCommitCollector}.
 * 
 * @author rsenden
 *
 */
public interface INcdReportRepositoryBranchCommitCollector {
    /**
     * Report a discovered branch commit
     * @param descriptor
     */
    void reportBranchCommit(NcdReportBranchCommitDescriptor descriptor);
}
