/*******************************************************************************
 * Copyright 2021, 2023 Open Text.
 *
 * The only warranties for products and services of Open Text 
 * and its affiliates and licensors (“Open Text”) are as may 
 * be set forth in the express warranty statements accompanying 
 * such products and services. Nothing herein should be construed 
 * as constituting an additional warranty. Open Text shall not be 
 * liable for technical or editorial errors or omissions contained 
 * herein. The information contained herein is subject to change 
 * without notice.
 *******************************************************************************/
package com.fortify.cli.util.ncd_report.collector;

import com.fortify.cli.util.ncd_report.descriptor.NcdReportBranchCommitDescriptor;

/**
 * This interface is to be implemented by classes that can collect
 * {@link NcdReportBranchCommitDescriptor} instances generated by
 * system-specific results generators. There is currently one class
 * that implements this interface: {@link NcdReportRepositoryBranchCommitCollector}.
 * 
 * @author rsenden
 *
 */
public interface INcdReportRepositoryBranchCommitCollector {
    /**
     * Report a discovered branch commit
     * @param descriptor
     */
    void reportBranchCommit(NcdReportBranchCommitDescriptor descriptor);
}
