package com.fortify.cli.util.ncd_report.collector;

import com.fortify.cli.util.ncd_report.config.INcdReportRepoSelectorConfig;
import com.fortify.cli.util.ncd_report.descriptor.INcdReportRepositoryDescriptor;
import com.fortify.cli.util.ncd_report.generator.INcdReportBranchCommitGenerator;

/**
 * This interface is to be implemented by classes that can process
 * {@link INcdReportRepositoryDescriptor} instances generated by
 * system-specific results generators. There is currently one class
 * that implements this interface: {@link NcdReportRepositoryProcessor}.
 * 
 * @author rsenden
 *
 */
public interface INcdReportRepositoryProcessor {
    /**
     * Process the repository described by the given {@link INcdReportRepositoryDescriptor}.
     * Based on the given {@link INcdReportRepoSelectorConfig}, implementations should
     * decide whether the repository should be processed or not. If the repository should 
     * be processed, the given {@link INcdReportBranchCommitGenerator} can be invoked to 
     * generate commit data for every branch in the given repository. 
     */
    <R extends INcdReportRepositoryDescriptor> void processRepository(INcdReportRepoSelectorConfig repoSelectorConfig, R repoDescriptor, INcdReportBranchCommitGenerator<R> commitGenerator);
}