//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.08.06 at 10:51:02 PM IST 
//


package com.fortify.cli.aviator.fpr.jaxb;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element ref="{xmlns://www.fortifysoftware.com/schema/fvdl}Dataflow" minOccurs="0"/&gt;
 *         &lt;element ref="{xmlns://www.fortifysoftware.com/schema/fvdl}Local" minOccurs="0"/&gt;
 *         &lt;element ref="{xmlns://www.fortifysoftware.com/schema/fvdl}Stateful" minOccurs="0"/&gt;
 *         &lt;element ref="{xmlns://www.fortifysoftware.com/schema/fvdl}Structural" minOccurs="0"/&gt;
 *         &lt;element ref="{xmlns://www.fortifysoftware.com/schema/fvdl}Configuration" minOccurs="0"/&gt;
 *         &lt;element ref="{xmlns://www.fortifysoftware.com/schema/fvdl}Unified" minOccurs="0"/&gt;
 *         &lt;element ref="{xmlns://www.fortifysoftware.com/schema/fvdl}Runtime" minOccurs="0"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dataflow",
    "local",
    "stateful",
    "structural",
    "configuration",
    "unified",
    "runtime"
})
@XmlRootElement(name = "AnalysisInfo")
public class AnalysisInfo {

    @XmlElement(name = "Dataflow")
    protected Dataflow dataflow;
    @XmlElement(name = "Local")
    protected Local local;
    @XmlElement(name = "Stateful")
    protected Stateful stateful;
    @XmlElement(name = "Structural")
    protected Structural structural;
    @XmlElement(name = "Configuration")
    protected Configuration configuration;
    @XmlElement(name = "Unified")
    protected Unified unified;
    @XmlElement(name = "Runtime")
    protected Runtime runtime;

    /**
     * Gets the value of the dataflow property.
     * 
     * @return
     *     possible object is
     *     {@link Dataflow }
     *     
     */
    public Dataflow getDataflow() {
        return dataflow;
    }

    /**
     * Sets the value of the dataflow property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dataflow }
     *     
     */
    public void setDataflow(Dataflow value) {
        this.dataflow = value;
    }

    /**
     * Gets the value of the local property.
     * 
     * @return
     *     possible object is
     *     {@link Local }
     *     
     */
    public Local getLocal() {
        return local;
    }

    /**
     * Sets the value of the local property.
     * 
     * @param value
     *     allowed object is
     *     {@link Local }
     *     
     */
    public void setLocal(Local value) {
        this.local = value;
    }

    /**
     * Gets the value of the stateful property.
     * 
     * @return
     *     possible object is
     *     {@link Stateful }
     *     
     */
    public Stateful getStateful() {
        return stateful;
    }

    /**
     * Sets the value of the stateful property.
     * 
     * @param value
     *     allowed object is
     *     {@link Stateful }
     *     
     */
    public void setStateful(Stateful value) {
        this.stateful = value;
    }

    /**
     * Gets the value of the structural property.
     * 
     * @return
     *     possible object is
     *     {@link Structural }
     *     
     */
    public Structural getStructural() {
        return structural;
    }

    /**
     * Sets the value of the structural property.
     * 
     * @param value
     *     allowed object is
     *     {@link Structural }
     *     
     */
    public void setStructural(Structural value) {
        this.structural = value;
    }

    /**
     * Gets the value of the configuration property.
     * 
     * @return
     *     possible object is
     *     {@link Configuration }
     *     
     */
    public Configuration getConfiguration() {
        return configuration;
    }

    /**
     * Sets the value of the configuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Configuration }
     *     
     */
    public void setConfiguration(Configuration value) {
        this.configuration = value;
    }

    /**
     * Gets the value of the unified property.
     * 
     * @return
     *     possible object is
     *     {@link Unified }
     *     
     */
    public Unified getUnified() {
        return unified;
    }

    /**
     * Sets the value of the unified property.
     * 
     * @param value
     *     allowed object is
     *     {@link Unified }
     *     
     */
    public void setUnified(Unified value) {
        this.unified = value;
    }

    /**
     * Gets the value of the runtime property.
     * 
     * @return
     *     possible object is
     *     {@link Runtime }
     *     
     */
    public Runtime getRuntime() {
        return runtime;
    }

    /**
     * Sets the value of the runtime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Runtime }
     *     
     */
    public void setRuntime(Runtime value) {
        this.runtime = value;
    }

}
