//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.08.06 at 10:51:02 PM IST 
//


package com.fortify.cli.aviator.fpr.jaxb;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Project" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Version" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Label" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="BuildID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="BuildDuration" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="NumberFiles" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element ref="{xmlns://www.fortifysoftware.com/schema/fvdl}LOC" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="JavaClasspath" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Libdirs" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SourceBasePath" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SourceFiles" type="{xmlns://www.fortifysoftware.com/schema/fvdl}FileList" minOccurs="0"/&gt;
 *         &lt;element name="ScanTime" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "project",
    "version",
    "label",
    "buildID",
    "buildDuration",
    "numberFiles",
    "loc",
    "javaClasspath",
    "libdirs",
    "sourceBasePath",
    "sourceFiles",
    "scanTime"
})
@XmlRootElement(name = "Build")
public class Build {

    @XmlElement(name = "Project")
    protected String project;
    @XmlElement(name = "Version")
    protected String version;
    @XmlElement(name = "Label")
    protected String label;
    @XmlElement(name = "BuildID")
    protected String buildID;
    @XmlElement(name = "BuildDuration")
    protected Integer buildDuration;
    @XmlElement(name = "NumberFiles")
    protected Integer numberFiles;
    @XmlElement(name = "LOC")
    protected List<LOC> loc;
    @XmlElement(name = "JavaClasspath")
    protected String javaClasspath;
    @XmlElement(name = "Libdirs")
    protected String libdirs;
    @XmlElement(name = "SourceBasePath")
    protected String sourceBasePath;
    @XmlElement(name = "SourceFiles")
    protected FileList sourceFiles;
    @XmlElement(name = "ScanTime")
    protected Build.ScanTime scanTime;

    /**
     * Gets the value of the project property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProject() {
        return project;
    }

    /**
     * Sets the value of the project property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProject(String value) {
        this.project = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets the value of the buildID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBuildID() {
        return buildID;
    }

    /**
     * Sets the value of the buildID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBuildID(String value) {
        this.buildID = value;
    }

    /**
     * Gets the value of the buildDuration property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getBuildDuration() {
        return buildDuration;
    }

    /**
     * Sets the value of the buildDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setBuildDuration(Integer value) {
        this.buildDuration = value;
    }

    /**
     * Gets the value of the numberFiles property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumberFiles() {
        return numberFiles;
    }

    /**
     * Sets the value of the numberFiles property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumberFiles(Integer value) {
        this.numberFiles = value;
    }

    /**
     * Total number of lines of code scanned Gets the value of the loc property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the loc property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLOC().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LOC }
     * 
     * 
     */
    public List<LOC> getLOC() {
        if (loc == null) {
            loc = new ArrayList<LOC>();
        }
        return this.loc;
    }

    /**
     * Gets the value of the javaClasspath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJavaClasspath() {
        return javaClasspath;
    }

    /**
     * Sets the value of the javaClasspath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJavaClasspath(String value) {
        this.javaClasspath = value;
    }

    /**
     * Gets the value of the libdirs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLibdirs() {
        return libdirs;
    }

    /**
     * Sets the value of the libdirs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLibdirs(String value) {
        this.libdirs = value;
    }

    /**
     * Gets the value of the sourceBasePath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceBasePath() {
        return sourceBasePath;
    }

    /**
     * Sets the value of the sourceBasePath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceBasePath(String value) {
        this.sourceBasePath = value;
    }

    /**
     * Gets the value of the sourceFiles property.
     * 
     * @return
     *     possible object is
     *     {@link FileList }
     *     
     */
    public FileList getSourceFiles() {
        return sourceFiles;
    }

    /**
     * Sets the value of the sourceFiles property.
     * 
     * @param value
     *     allowed object is
     *     {@link FileList }
     *     
     */
    public void setSourceFiles(FileList value) {
        this.sourceFiles = value;
    }

    /**
     * Gets the value of the scanTime property.
     * 
     * @return
     *     possible object is
     *     {@link Build.ScanTime }
     *     
     */
    public Build.ScanTime getScanTime() {
        return scanTime;
    }

    /**
     * Sets the value of the scanTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Build.ScanTime }
     *     
     */
    public void setScanTime(Build.ScanTime value) {
        this.scanTime = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class ScanTime {

        @XmlAttribute(name = "value", required = true)
        protected BigInteger value;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setValue(BigInteger value) {
            this.value = value;
        }

    }

}
