//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.08.06 at 10:51:02 PM IST 
//


package com.fortify.cli.aviator.fpr.jaxb;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Base type for dataflow node elements
 * 
 * <p>Java class for dataflowNode complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="dataflowNode"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{xmlns://www.fortifysoftware.com/schema/fvdl}SourceRef"/&gt;
 *         &lt;element ref="{xmlns://www.fortifysoftware.com/schema/fvdl}Context" minOccurs="0"/&gt;
 *         &lt;element name="Label" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element ref="{xmlns://www.fortifysoftware.com/schema/fvdl}ExternalID" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="inArg" type="{xmlns://www.fortifysoftware.com/schema/fvdl}argSpecifier" /&gt;
 *       &lt;attribute name="outArg" type="{xmlns://www.fortifysoftware.com/schema/fvdl}argSpecifier" /&gt;
 *       &lt;attribute name="inParameterName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="outParameterName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ruleID" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dataflowNode", propOrder = {
    "sourceRef",
    "context",
    "label",
    "externalID"
})
@XmlSeeAlso({
    Node.class,
    Sink.class,
    Source.class
})
public class DataflowNode {

    @XmlElement(name = "SourceRef", required = true)
    protected SourceRef sourceRef;
    @XmlElement(name = "Context")
    protected Context context;
    @XmlElement(name = "Label")
    protected String label;
    @XmlElement(name = "ExternalID")
    protected List<ExternalID> externalID;
    @XmlAttribute(name = "inArg")
    protected String inArg;
    @XmlAttribute(name = "outArg")
    protected String outArg;
    @XmlAttribute(name = "inParameterName")
    protected String inParameterName;
    @XmlAttribute(name = "outParameterName")
    protected String outParameterName;
    @XmlAttribute(name = "ruleID")
    protected String ruleID;

    /**
     * Gets the value of the sourceRef property.
     * 
     * @return
     *     possible object is
     *     {@link SourceRef }
     *     
     */
    public SourceRef getSourceRef() {
        return sourceRef;
    }

    /**
     * Sets the value of the sourceRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link SourceRef }
     *     
     */
    public void setSourceRef(SourceRef value) {
        this.sourceRef = value;
    }

    /**
     * Gets the value of the context property.
     * 
     * @return
     *     possible object is
     *     {@link Context }
     *     
     */
    public Context getContext() {
        return context;
    }

    /**
     * Sets the value of the context property.
     * 
     * @param value
     *     allowed object is
     *     {@link Context }
     *     
     */
    public void setContext(Context value) {
        this.context = value;
    }

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets the value of the externalID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the externalID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExternalID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExternalID }
     * 
     * 
     */
    public List<ExternalID> getExternalID() {
        if (externalID == null) {
            externalID = new ArrayList<ExternalID>();
        }
        return this.externalID;
    }

    /**
     * Gets the value of the inArg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInArg() {
        return inArg;
    }

    /**
     * Sets the value of the inArg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInArg(String value) {
        this.inArg = value;
    }

    /**
     * Gets the value of the outArg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutArg() {
        return outArg;
    }

    /**
     * Sets the value of the outArg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutArg(String value) {
        this.outArg = value;
    }

    /**
     * Gets the value of the inParameterName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInParameterName() {
        return inParameterName;
    }

    /**
     * Sets the value of the inParameterName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInParameterName(String value) {
        this.inParameterName = value;
    }

    /**
     * Gets the value of the outParameterName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutParameterName() {
        return outParameterName;
    }

    /**
     * Sets the value of the outParameterName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutParameterName(String value) {
        this.outParameterName = value;
    }

    /**
     * Gets the value of the ruleID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRuleID() {
        return ruleID;
    }

    /**
     * Sets the value of the ruleID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRuleID(String value) {
        this.ruleID = value;
    }

}
