//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.08.06 at 10:51:02 PM IST 
//


package com.fortify.cli.aviator.fpr.jaxb;
import java.util.ArrayList;
import java.util.List;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="EngineVersion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element ref="{xmlns://www.fortifysoftware.com/schema/fvdl}InactiveResults" minOccurs="0"/&gt;
 *         &lt;element name="RulePacks" type="{xmlns://www.fortifysoftware.com/schema/fvdl}RulePackList" minOccurs="0"/&gt;
 *         &lt;element name="ExpiredRulePacks" type="{xmlns://www.fortifysoftware.com/schema/fvdl}RulePackList" minOccurs="0"/&gt;
 *         &lt;element name="UnlicensedRulePacks" type="{xmlns://www.fortifysoftware.com/schema/fvdl}RulePackList" minOccurs="0"/&gt;
 *         &lt;element name="Properties" type="{xmlns://www.fortifysoftware.com/schema/fvdl}Propertylist" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="CommandLine" type="{xmlns://www.fortifysoftware.com/schema/fvdl}commandlinetype" minOccurs="0"/&gt;
 *         &lt;element name="Errors" type="{xmlns://www.fortifysoftware.com/schema/fvdl}errMsg" minOccurs="0"/&gt;
 *         &lt;element name="MachineInfo" type="{xmlns://www.fortifysoftware.com/schema/fvdl}machineinfodetail" minOccurs="0"/&gt;
 *         &lt;element name="FilterResult" type="{xmlns://www.fortifysoftware.com/schema/fvdl}filter" minOccurs="0"/&gt;
 *         &lt;element name="RuleInfo" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Rule" maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="MetaInfo" type="{xmlns://www.fortifysoftware.com/schema/fvdl}metaInfo" minOccurs="0"/&gt;
 *                           &lt;/sequence&gt;
 *                           &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="LicenseInfo" type="{xmlns://www.fortifysoftware.com/schema/fvdl}licenseinfo" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "engineVersion",
    "inactiveResults",
    "rulePacks",
    "expiredRulePacks",
    "unlicensedRulePacks",
    "properties",
    "commandLine",
    "errors",
    "machineInfo",
    "filterResult",
    "ruleInfo",
    "licenseInfo"
})
@XmlRootElement(name = "EngineData")
public class EngineData {

    @XmlElement(name = "EngineVersion")
    protected String engineVersion;
    @XmlElement(name = "InactiveResults")
    protected InactiveResults inactiveResults;
    @XmlElement(name = "RulePacks")
    protected RulePackList rulePacks;
    @XmlElement(name = "ExpiredRulePacks")
    protected RulePackList expiredRulePacks;
    @XmlElement(name = "UnlicensedRulePacks")
    protected RulePackList unlicensedRulePacks;
    @XmlElement(name = "Properties")
    protected List<Propertylist> properties;
    @XmlElement(name = "CommandLine")
    protected Commandlinetype commandLine;
    @XmlElement(name = "Errors")
    protected ErrMsg errors;
    @XmlElement(name = "MachineInfo")
    protected Machineinfodetail machineInfo;
    @XmlElement(name = "FilterResult")
    protected Filter filterResult;
    @XmlElement(name = "RuleInfo")
    protected EngineData.RuleInfo ruleInfo;
    @XmlElement(name = "LicenseInfo")
    protected Licenseinfo licenseInfo;

    /**
     * Gets the value of the engineVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEngineVersion() {
        return engineVersion;
    }

    /**
     * Sets the value of the engineVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEngineVersion(String value) {
        this.engineVersion = value;
    }

    /**
     * Gets the value of the inactiveResults property.
     * 
     * @return
     *     possible object is
     *     {@link InactiveResults }
     *     
     */
    public InactiveResults getInactiveResults() {
        return inactiveResults;
    }

    /**
     * Sets the value of the inactiveResults property.
     * 
     * @param value
     *     allowed object is
     *     {@link InactiveResults }
     *     
     */
    public void setInactiveResults(InactiveResults value) {
        this.inactiveResults = value;
    }

    /**
     * Gets the value of the rulePacks property.
     * 
     * @return
     *     possible object is
     *     {@link RulePackList }
     *     
     */
    public RulePackList getRulePacks() {
        return rulePacks;
    }

    /**
     * Sets the value of the rulePacks property.
     * 
     * @param value
     *     allowed object is
     *     {@link RulePackList }
     *     
     */
    public void setRulePacks(RulePackList value) {
        this.rulePacks = value;
    }

    /**
     * Gets the value of the expiredRulePacks property.
     * 
     * @return
     *     possible object is
     *     {@link RulePackList }
     *     
     */
    public RulePackList getExpiredRulePacks() {
        return expiredRulePacks;
    }

    /**
     * Sets the value of the expiredRulePacks property.
     * 
     * @param value
     *     allowed object is
     *     {@link RulePackList }
     *     
     */
    public void setExpiredRulePacks(RulePackList value) {
        this.expiredRulePacks = value;
    }

    /**
     * Gets the value of the unlicensedRulePacks property.
     * 
     * @return
     *     possible object is
     *     {@link RulePackList }
     *     
     */
    public RulePackList getUnlicensedRulePacks() {
        return unlicensedRulePacks;
    }

    /**
     * Sets the value of the unlicensedRulePacks property.
     * 
     * @param value
     *     allowed object is
     *     {@link RulePackList }
     *     
     */
    public void setUnlicensedRulePacks(RulePackList value) {
        this.unlicensedRulePacks = value;
    }

    /**
     * Gets the value of the properties property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the properties property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProperties().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Propertylist }
     * 
     * 
     */
    public List<Propertylist> getProperties() {
        if (properties == null) {
            properties = new ArrayList<Propertylist>();
        }
        return this.properties;
    }

    /**
     * Gets the value of the commandLine property.
     * 
     * @return
     *     possible object is
     *     {@link Commandlinetype }
     *     
     */
    public Commandlinetype getCommandLine() {
        return commandLine;
    }

    /**
     * Sets the value of the commandLine property.
     * 
     * @param value
     *     allowed object is
     *     {@link Commandlinetype }
     *     
     */
    public void setCommandLine(Commandlinetype value) {
        this.commandLine = value;
    }

    /**
     * Gets the value of the errors property.
     * 
     * @return
     *     possible object is
     *     {@link ErrMsg }
     *     
     */
    public ErrMsg getErrors() {
        return errors;
    }

    /**
     * Sets the value of the errors property.
     * 
     * @param value
     *     allowed object is
     *     {@link ErrMsg }
     *     
     */
    public void setErrors(ErrMsg value) {
        this.errors = value;
    }

    /**
     * Gets the value of the machineInfo property.
     * 
     * @return
     *     possible object is
     *     {@link Machineinfodetail }
     *     
     */
    public Machineinfodetail getMachineInfo() {
        return machineInfo;
    }

    /**
     * Sets the value of the machineInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Machineinfodetail }
     *     
     */
    public void setMachineInfo(Machineinfodetail value) {
        this.machineInfo = value;
    }

    /**
     * Gets the value of the filterResult property.
     * 
     * @return
     *     possible object is
     *     {@link Filter }
     *     
     */
    public Filter getFilterResult() {
        return filterResult;
    }

    /**
     * Sets the value of the filterResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link Filter }
     *     
     */
    public void setFilterResult(Filter value) {
        this.filterResult = value;
    }

    /**
     * Gets the value of the ruleInfo property.
     * 
     * @return
     *     possible object is
     *     {@link EngineData.RuleInfo }
     *     
     */
    public EngineData.RuleInfo getRuleInfo() {
        return ruleInfo;
    }

    /**
     * Sets the value of the ruleInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link EngineData.RuleInfo }
     *     
     */
    public void setRuleInfo(EngineData.RuleInfo value) {
        this.ruleInfo = value;
    }

    /**
     * Gets the value of the licenseInfo property.
     * 
     * @return
     *     possible object is
     *     {@link Licenseinfo }
     *     
     */
    public Licenseinfo getLicenseInfo() {
        return licenseInfo;
    }

    /**
     * Sets the value of the licenseInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Licenseinfo }
     *     
     */
    public void setLicenseInfo(Licenseinfo value) {
        this.licenseInfo = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Rule" maxOccurs="unbounded" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="MetaInfo" type="{xmlns://www.fortifysoftware.com/schema/fvdl}metaInfo" minOccurs="0"/&gt;
     *                 &lt;/sequence&gt;
     *                 &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "rule"
    })
    public static class RuleInfo {

        @XmlElement(name = "Rule")
        protected List<EngineData.RuleInfo.Rule> rule;

        /**
         * Gets the value of the rule property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the rule property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRule().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link EngineData.RuleInfo.Rule }
         * 
         * 
         */
        public List<EngineData.RuleInfo.Rule> getRule() {
            if (rule == null) {
                rule = new ArrayList<EngineData.RuleInfo.Rule>();
            }
            return this.rule;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="MetaInfo" type="{xmlns://www.fortifysoftware.com/schema/fvdl}metaInfo" minOccurs="0"/&gt;
         *       &lt;/sequence&gt;
         *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "metaInfo"
        })
        public static class Rule {

            @XmlElement(name = "MetaInfo")
            protected MetaInfo metaInfo;
            @XmlAttribute(name = "id", required = true)
            protected String id;

            /**
             * Gets the value of the metaInfo property.
             * 
             * @return
             *     possible object is
             *     {@link MetaInfo }
             *     
             */
            public MetaInfo getMetaInfo() {
                return metaInfo;
            }

            /**
             * Sets the value of the metaInfo property.
             * 
             * @param value
             *     allowed object is
             *     {@link MetaInfo }
             *     
             */
            public void setMetaInfo(MetaInfo value) {
                this.metaInfo = value;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

        }

    }

}
