//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.08.06 at 10:51:02 PM IST 
//


package com.fortify.cli.aviator.fpr.jaxb;
import java.util.ArrayList;
import java.util.List;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CreatedTS" type="{xmlns://www.fortifysoftware.com/schema/fvdl}timeStamp"/&gt;
 *         &lt;element name="WriteDate" type="{xmlns://www.fortifysoftware.com/schema/fvdl}timeStamp" minOccurs="0"/&gt;
 *         &lt;element name="ModifiedDate" type="{xmlns://www.fortifysoftware.com/schema/fvdl}timeStamp" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="ModifiedTS" type="{xmlns://www.fortifysoftware.com/schema/fvdl}timeStamp" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="UUID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element ref="{xmlns://www.fortifysoftware.com/schema/fvdl}Build" minOccurs="0"/&gt;
 *         &lt;element ref="{xmlns://www.fortifysoftware.com/schema/fvdl}Vulnerabilities" minOccurs="0"/&gt;
 *         &lt;element ref="{xmlns://www.fortifysoftware.com/schema/fvdl}ContextPool" minOccurs="0"/&gt;
 *         &lt;element ref="{xmlns://www.fortifysoftware.com/schema/fvdl}UnifiedNodePool" minOccurs="0"/&gt;
 *         &lt;element ref="{xmlns://www.fortifysoftware.com/schema/fvdl}UnifiedTracePool" minOccurs="0"/&gt;
 *         &lt;element ref="{xmlns://www.fortifysoftware.com/schema/fvdl}UnifiedInductionPool" minOccurs="0"/&gt;
 *         &lt;element ref="{xmlns://www.fortifysoftware.com/schema/fvdl}DataflowPool" minOccurs="0"/&gt;
 *         &lt;element ref="{xmlns://www.fortifysoftware.com/schema/fvdl}SecondaryDataflow" minOccurs="0"/&gt;
 *         &lt;element ref="{xmlns://www.fortifysoftware.com/schema/fvdl}Description" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{xmlns://www.fortifysoftware.com/schema/fvdl}Snippets" minOccurs="0"/&gt;
 *         &lt;element ref="{xmlns://www.fortifysoftware.com/schema/fvdl}ProgramData" minOccurs="0"/&gt;
 *         &lt;element ref="{xmlns://www.fortifysoftware.com/schema/fvdl}EngineData" minOccurs="0"/&gt;
 *         &lt;element ref="{xmlns://www.fortifysoftware.com/schema/fvdl}SupplementalData" minOccurs="0"/&gt;
 *         &lt;element ref="{xmlns://www.fortifysoftware.com/schema/fvdl}ExternalID" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "createdTS",
    "writeDate",
    "modifiedDate",
    "modifiedTS",
    "uuid",
    "build",
    "vulnerabilities",
    "contextPool",
    "unifiedNodePool",
    "unifiedTracePool",
    "unifiedInductionPool",
    "dataflowPool",
    "secondaryDataflow",
    "description",
    "snippets",
    "programData",
    "engineData",
    "supplementalData",
    "externalID"
})
@XmlRootElement(name = "FVDL")
public class FVDL {

    @XmlElement(name = "CreatedTS", required = true)
    protected TimeStamp createdTS;
    @XmlElement(name = "WriteDate")
    protected TimeStamp writeDate;
    @XmlElement(name = "ModifiedDate")
    protected List<TimeStamp> modifiedDate;
    @XmlElement(name = "ModifiedTS")
    protected List<TimeStamp> modifiedTS;
    @XmlElement(name = "UUID")
    protected String uuid;
    @XmlElement(name = "Build")
    protected Build build;
    @XmlElement(name = "Vulnerabilities")
    protected Vulnerabilities vulnerabilities;
    @XmlElement(name = "ContextPool")
    protected ContextPool contextPool;
    @XmlElement(name = "UnifiedNodePool")
    protected UnifiedNodePoolType unifiedNodePool;
    @XmlElement(name = "UnifiedTracePool")
    protected UnifiedTracePool unifiedTracePool;
    @XmlElement(name = "UnifiedInductionPool")
    protected UnifiedInductionPool unifiedInductionPool;
    @XmlElement(name = "DataflowPool")
    protected DataflowPool dataflowPool;
    @XmlElement(name = "SecondaryDataflow")
    protected SecondaryDataflow secondaryDataflow;
    @XmlElement(name = "Description")
    protected List<Description> description;
    @XmlElement(name = "Snippets")
    protected Snippets snippets;
    @XmlElement(name = "ProgramData")
    protected ProgramData programData;
    @XmlElement(name = "EngineData")
    protected EngineData engineData;
    @XmlElement(name = "SupplementalData")
    protected SupplementalData supplementalData;
    @XmlElement(name = "ExternalID")
    protected List<ExternalID> externalID;
    @XmlAttribute(name = "version", required = true)
    protected String version;

    /**
     * Gets the value of the createdTS property.
     * 
     * @return
     *     possible object is
     *     {@link TimeStamp }
     *     
     */
    public TimeStamp getCreatedTS() {
        return createdTS;
    }

    /**
     * Sets the value of the createdTS property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeStamp }
     *     
     */
    public void setCreatedTS(TimeStamp value) {
        this.createdTS = value;
    }

    /**
     * Gets the value of the writeDate property.
     * 
     * @return
     *     possible object is
     *     {@link TimeStamp }
     *     
     */
    public TimeStamp getWriteDate() {
        return writeDate;
    }

    /**
     * Sets the value of the writeDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeStamp }
     *     
     */
    public void setWriteDate(TimeStamp value) {
        this.writeDate = value;
    }

    /**
     * Gets the value of the modifiedDate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the modifiedDate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getModifiedDate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TimeStamp }
     * 
     * 
     */
    public List<TimeStamp> getModifiedDate() {
        if (modifiedDate == null) {
            modifiedDate = new ArrayList<TimeStamp>();
        }
        return this.modifiedDate;
    }

    /**
     * Gets the value of the modifiedTS property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the modifiedTS property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getModifiedTS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TimeStamp }
     * 
     * 
     */
    public List<TimeStamp> getModifiedTS() {
        if (modifiedTS == null) {
            modifiedTS = new ArrayList<TimeStamp>();
        }
        return this.modifiedTS;
    }

    /**
     * Gets the value of the uuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUUID() {
        return uuid;
    }

    /**
     * Sets the value of the uuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUUID(String value) {
        this.uuid = value;
    }

    /**
     * Gets the value of the build property.
     * 
     * @return
     *     possible object is
     *     {@link Build }
     *     
     */
    public Build getBuild() {
        return build;
    }

    /**
     * Sets the value of the build property.
     * 
     * @param value
     *     allowed object is
     *     {@link Build }
     *     
     */
    public void setBuild(Build value) {
        this.build = value;
    }

    /**
     * Gets the value of the vulnerabilities property.
     * 
     * @return
     *     possible object is
     *     {@link Vulnerabilities }
     *     
     */
    public Vulnerabilities getVulnerabilities() {
        return vulnerabilities;
    }

    /**
     * Sets the value of the vulnerabilities property.
     * 
     * @param value
     *     allowed object is
     *     {@link Vulnerabilities }
     *     
     */
    public void setVulnerabilities(Vulnerabilities value) {
        this.vulnerabilities = value;
    }

    /**
     * Gets the value of the contextPool property.
     * 
     * @return
     *     possible object is
     *     {@link ContextPool }
     *     
     */
    public ContextPool getContextPool() {
        return contextPool;
    }

    /**
     * Sets the value of the contextPool property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContextPool }
     *     
     */
    public void setContextPool(ContextPool value) {
        this.contextPool = value;
    }

    /**
     * Gets the value of the unifiedNodePool property.
     * 
     * @return
     *     possible object is
     *     {@link UnifiedNodePoolType }
     *     
     */
    public UnifiedNodePoolType getUnifiedNodePool() {
        return unifiedNodePool;
    }

    /**
     * Sets the value of the unifiedNodePool property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnifiedNodePoolType }
     *     
     */
    public void setUnifiedNodePool(UnifiedNodePoolType value) {
        this.unifiedNodePool = value;
    }

    /**
     * Gets the value of the unifiedTracePool property.
     * 
     * @return
     *     possible object is
     *     {@link UnifiedTracePool }
     *     
     */
    public UnifiedTracePool getUnifiedTracePool() {
        return unifiedTracePool;
    }

    /**
     * Sets the value of the unifiedTracePool property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnifiedTracePool }
     *     
     */
    public void setUnifiedTracePool(UnifiedTracePool value) {
        this.unifiedTracePool = value;
    }

    /**
     * Gets the value of the unifiedInductionPool property.
     * 
     * @return
     *     possible object is
     *     {@link UnifiedInductionPool }
     *     
     */
    public UnifiedInductionPool getUnifiedInductionPool() {
        return unifiedInductionPool;
    }

    /**
     * Sets the value of the unifiedInductionPool property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnifiedInductionPool }
     *     
     */
    public void setUnifiedInductionPool(UnifiedInductionPool value) {
        this.unifiedInductionPool = value;
    }

    /**
     * Gets the value of the dataflowPool property.
     * 
     * @return
     *     possible object is
     *     {@link DataflowPool }
     *     
     */
    public DataflowPool getDataflowPool() {
        return dataflowPool;
    }

    /**
     * Sets the value of the dataflowPool property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataflowPool }
     *     
     */
    public void setDataflowPool(DataflowPool value) {
        this.dataflowPool = value;
    }

    /**
     * Gets the value of the secondaryDataflow property.
     * 
     * @return
     *     possible object is
     *     {@link SecondaryDataflow }
     *     
     */
    public SecondaryDataflow getSecondaryDataflow() {
        return secondaryDataflow;
    }

    /**
     * Sets the value of the secondaryDataflow property.
     * 
     * @param value
     *     allowed object is
     *     {@link SecondaryDataflow }
     *     
     */
    public void setSecondaryDataflow(SecondaryDataflow value) {
        this.secondaryDataflow = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the description property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Description }
     * 
     * 
     */
    public List<Description> getDescription() {
        if (description == null) {
            description = new ArrayList<Description>();
        }
        return this.description;
    }

    /**
     * Gets the value of the snippets property.
     * 
     * @return
     *     possible object is
     *     {@link Snippets }
     *     
     */
    public Snippets getSnippets() {
        return snippets;
    }

    /**
     * Sets the value of the snippets property.
     * 
     * @param value
     *     allowed object is
     *     {@link Snippets }
     *     
     */
    public void setSnippets(Snippets value) {
        this.snippets = value;
    }

    /**
     * Gets the value of the programData property.
     * 
     * @return
     *     possible object is
     *     {@link ProgramData }
     *     
     */
    public ProgramData getProgramData() {
        return programData;
    }

    /**
     * Sets the value of the programData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProgramData }
     *     
     */
    public void setProgramData(ProgramData value) {
        this.programData = value;
    }

    /**
     * Gets the value of the engineData property.
     * 
     * @return
     *     possible object is
     *     {@link EngineData }
     *     
     */
    public EngineData getEngineData() {
        return engineData;
    }

    /**
     * Sets the value of the engineData property.
     * 
     * @param value
     *     allowed object is
     *     {@link EngineData }
     *     
     */
    public void setEngineData(EngineData value) {
        this.engineData = value;
    }

    /**
     * Gets the value of the supplementalData property.
     * 
     * @return
     *     possible object is
     *     {@link SupplementalData }
     *     
     */
    public SupplementalData getSupplementalData() {
        return supplementalData;
    }

    /**
     * Sets the value of the supplementalData property.
     * 
     * @param value
     *     allowed object is
     *     {@link SupplementalData }
     *     
     */
    public void setSupplementalData(SupplementalData value) {
        this.supplementalData = value;
    }

    /**
     * Gets the value of the externalID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the externalID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExternalID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExternalID }
     * 
     * 
     */
    public List<ExternalID> getExternalID() {
        if (externalID == null) {
            externalID = new ArrayList<ExternalID>();
        }
        return this.externalID;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
