//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.08.06 at 10:51:02 PM IST 
//


package com.fortify.cli.aviator.fpr.jaxb;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{xmlns://www.fortifysoftware.com/schema/fvdl}InstanceID"/&gt;
 *         &lt;element ref="{xmlns://www.fortifysoftware.com/schema/fvdl}InstanceSeverity" minOccurs="0"/&gt;
 *         &lt;element ref="{xmlns://www.fortifysoftware.com/schema/fvdl}InstanceDescription" minOccurs="0"/&gt;
 *         &lt;element ref="{xmlns://www.fortifysoftware.com/schema/fvdl}Audits" minOccurs="0"/&gt;
 *         &lt;element name="Confidence" type="{xmlns://www.fortifysoftware.com/schema/fvdl}severityType" minOccurs="0"/&gt;
 *         &lt;element name="MetaInfo" type="{xmlns://www.fortifysoftware.com/schema/fvdl}metaInfo" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="MinVirtualCallConfidence" type="{xmlns://www.fortifysoftware.com/schema/fvdl}float0to1" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "instanceID",
    "instanceSeverity",
    "instanceDescription",
    "audits",
    "confidence",
    "metaInfo"
})
@XmlRootElement(name = "InstanceInfo")
public class InstanceInfo {

    @XmlElement(name = "InstanceID", required = true)
    protected String instanceID;
    @XmlElement(name = "InstanceSeverity")
    protected Float instanceSeverity;
    @XmlElement(name = "InstanceDescription")
    protected String instanceDescription;
    @XmlElement(name = "Audits")
    protected Audits audits;
    @XmlElement(name = "Confidence")
    protected Float confidence;
    @XmlElement(name = "MetaInfo")
    protected MetaInfo metaInfo;
    @XmlAttribute(name = "MinVirtualCallConfidence")
    protected Float minVirtualCallConfidence;

    /**
     * Gets the value of the instanceID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstanceID() {
        return instanceID;
    }

    /**
     * Sets the value of the instanceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstanceID(String value) {
        this.instanceID = value;
    }

    /**
     * Gets the value of the instanceSeverity property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getInstanceSeverity() {
        return instanceSeverity;
    }

    /**
     * Sets the value of the instanceSeverity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setInstanceSeverity(Float value) {
        this.instanceSeverity = value;
    }

    /**
     * Gets the value of the instanceDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstanceDescription() {
        return instanceDescription;
    }

    /**
     * Sets the value of the instanceDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstanceDescription(String value) {
        this.instanceDescription = value;
    }

    /**
     * Gets the value of the audits property.
     * 
     * @return
     *     possible object is
     *     {@link Audits }
     *     
     */
    public Audits getAudits() {
        return audits;
    }

    /**
     * Sets the value of the audits property.
     * 
     * @param value
     *     allowed object is
     *     {@link Audits }
     *     
     */
    public void setAudits(Audits value) {
        this.audits = value;
    }

    /**
     * Gets the value of the confidence property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getConfidence() {
        return confidence;
    }

    /**
     * Sets the value of the confidence property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setConfidence(Float value) {
        this.confidence = value;
    }

    /**
     * Gets the value of the metaInfo property.
     * 
     * @return
     *     possible object is
     *     {@link MetaInfo }
     *     
     */
    public MetaInfo getMetaInfo() {
        return metaInfo;
    }

    /**
     * Sets the value of the metaInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link MetaInfo }
     *     
     */
    public void setMetaInfo(MetaInfo value) {
        this.metaInfo = value;
    }

    /**
     * Gets the value of the minVirtualCallConfidence property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getMinVirtualCallConfidence() {
        return minVirtualCallConfidence;
    }

    /**
     * Sets the value of the minVirtualCallConfidence property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setMinVirtualCallConfidence(Float value) {
        this.minVirtualCallConfidence = value;
    }

}
