//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.08.06 at 10:51:02 PM IST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "xmlns://www.fortifysoftware.com/schema/fvdl", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.fortify.cli.aviator.fpr.jaxb;