//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.08.06 at 10:51:02 PM IST 
//


package com.fortify.cli.aviator.fpr.jaxb;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{xmlns://www.fortifysoftware.com/schema/fvdl}Sources"/&gt;
 *         &lt;element ref="{xmlns://www.fortifysoftware.com/schema/fvdl}Sinks"/&gt;
 *         &lt;element ref="{xmlns://www.fortifysoftware.com/schema/fvdl}CalledWithNoDef"/&gt;
 *         &lt;element ref="{xmlns://www.fortifysoftware.com/schema/fvdl}CalledWithTaint" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sources",
    "sinks",
    "calledWithNoDef",
    "calledWithTaint"
})
@XmlRootElement(name = "ProgramData")
public class ProgramData {

    @XmlElement(name = "Sources", required = true)
    protected Sources sources;
    @XmlElement(name = "Sinks", required = true)
    protected Sinks sinks;
    @XmlElement(name = "CalledWithNoDef", required = true)
    protected CalledWithNoDef calledWithNoDef;
    @XmlElement(name = "CalledWithTaint")
    protected CalledWithTaint calledWithTaint;

    /**
     * Gets the value of the sources property.
     * 
     * @return
     *     possible object is
     *     {@link Sources }
     *     
     */
    public Sources getSources() {
        return sources;
    }

    /**
     * Sets the value of the sources property.
     * 
     * @param value
     *     allowed object is
     *     {@link Sources }
     *     
     */
    public void setSources(Sources value) {
        this.sources = value;
    }

    /**
     * Gets the value of the sinks property.
     * 
     * @return
     *     possible object is
     *     {@link Sinks }
     *     
     */
    public Sinks getSinks() {
        return sinks;
    }

    /**
     * Sets the value of the sinks property.
     * 
     * @param value
     *     allowed object is
     *     {@link Sinks }
     *     
     */
    public void setSinks(Sinks value) {
        this.sinks = value;
    }

    /**
     * Gets the value of the calledWithNoDef property.
     * 
     * @return
     *     possible object is
     *     {@link CalledWithNoDef }
     *     
     */
    public CalledWithNoDef getCalledWithNoDef() {
        return calledWithNoDef;
    }

    /**
     * Sets the value of the calledWithNoDef property.
     * 
     * @param value
     *     allowed object is
     *     {@link CalledWithNoDef }
     *     
     */
    public void setCalledWithNoDef(CalledWithNoDef value) {
        this.calledWithNoDef = value;
    }

    /**
     * Gets the value of the calledWithTaint property.
     * 
     * @return
     *     possible object is
     *     {@link CalledWithTaint }
     *     
     */
    public CalledWithTaint getCalledWithTaint() {
        return calledWithTaint;
    }

    /**
     * Sets the value of the calledWithTaint property.
     * 
     * @param value
     *     allowed object is
     *     {@link CalledWithTaint }
     *     
     */
    public void setCalledWithTaint(CalledWithTaint value) {
        this.calledWithTaint = value;
    }

}
