//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.08.06 at 10:51:02 PM IST 
//


package com.fortify.cli.aviator.fpr.jaxb;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{xmlns://www.fortifysoftware.com/schema/fvdl}Context" minOccurs="0"/&gt;
 *         &lt;element name="PrimaryLocation" type="{xmlns://www.fortifysoftware.com/schema/fvdl}sourceLocationType"/&gt;
 *         &lt;element ref="{xmlns://www.fortifysoftware.com/schema/fvdl}ReplacementDefinitions" minOccurs="0"/&gt;
 *         &lt;element ref="{xmlns://www.fortifysoftware.com/schema/fvdl}EventSequenceList"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "context",
    "primaryLocation",
    "replacementDefinitions",
    "eventSequenceList"
})
@XmlRootElement(name = "Runtime")
public class Runtime {

    @XmlElement(name = "Context")
    protected Context context;
    @XmlElement(name = "PrimaryLocation", required = true)
    protected SourceLocationType primaryLocation;
    @XmlElement(name = "ReplacementDefinitions")
    protected ReplacementDefinitions replacementDefinitions;
    @XmlElement(name = "EventSequenceList", required = true)
    protected EventSequenceList eventSequenceList;

    /**
     * Deprecated as of schema version 1.11.  Use PrimaryLocation instead
     * 
     * @return
     *     possible object is
     *     {@link Context }
     *     
     */
    public Context getContext() {
        return context;
    }

    /**
     * Sets the value of the context property.
     * 
     * @param value
     *     allowed object is
     *     {@link Context }
     *     
     */
    public void setContext(Context value) {
        this.context = value;
    }

    /**
     * Gets the value of the primaryLocation property.
     * 
     * @return
     *     possible object is
     *     {@link SourceLocationType }
     *     
     */
    public SourceLocationType getPrimaryLocation() {
        return primaryLocation;
    }

    /**
     * Sets the value of the primaryLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link SourceLocationType }
     *     
     */
    public void setPrimaryLocation(SourceLocationType value) {
        this.primaryLocation = value;
    }

    /**
     * Gets the value of the replacementDefinitions property.
     * 
     * @return
     *     possible object is
     *     {@link ReplacementDefinitions }
     *     
     */
    public ReplacementDefinitions getReplacementDefinitions() {
        return replacementDefinitions;
    }

    /**
     * Sets the value of the replacementDefinitions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReplacementDefinitions }
     *     
     */
    public void setReplacementDefinitions(ReplacementDefinitions value) {
        this.replacementDefinitions = value;
    }

    /**
     * Gets the value of the eventSequenceList property.
     * 
     * @return
     *     possible object is
     *     {@link EventSequenceList }
     *     
     */
    public EventSequenceList getEventSequenceList() {
        return eventSequenceList;
    }

    /**
     * Sets the value of the eventSequenceList property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventSequenceList }
     *     
     */
    public void setEventSequenceList(EventSequenceList value) {
        this.eventSequenceList = value;
    }

}
