//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.08.06 at 10:51:02 PM IST 
//


package com.fortify.cli.aviator.fpr.jaxb;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Settings" type="{xmlns://www.fortifysoftware.com/schema/fvdl}runtimesetting"/&gt;
 *         &lt;element name="Environment" type="{xmlns://www.fortifysoftware.com/schema/fvdl}runtimesetting"/&gt;
 *         &lt;element name="Rulepacks" type="{xmlns://www.fortifysoftware.com/schema/fvdl}RulePackList"/&gt;
 *         &lt;element name="DisabledRuleIds" type="{xmlns://www.fortifysoftware.com/schema/fvdl}runtimedisabledruleid" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "settings",
    "environment",
    "rulepacks",
    "disabledRuleIds"
})
@XmlRootElement(name = "RuntimeConfiguration")
public class RuntimeConfiguration {

    @XmlElement(name = "Id", required = true)
    protected String id;
    @XmlElement(name = "Settings", required = true)
    protected Runtimesetting settings;
    @XmlElement(name = "Environment", required = true)
    protected Runtimesetting environment;
    @XmlElement(name = "Rulepacks", required = true)
    protected RulePackList rulepacks;
    @XmlElement(name = "DisabledRuleIds")
    protected Runtimedisabledruleid disabledRuleIds;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the settings property.
     * 
     * @return
     *     possible object is
     *     {@link Runtimesetting }
     *     
     */
    public Runtimesetting getSettings() {
        return settings;
    }

    /**
     * Sets the value of the settings property.
     * 
     * @param value
     *     allowed object is
     *     {@link Runtimesetting }
     *     
     */
    public void setSettings(Runtimesetting value) {
        this.settings = value;
    }

    /**
     * Gets the value of the environment property.
     * 
     * @return
     *     possible object is
     *     {@link Runtimesetting }
     *     
     */
    public Runtimesetting getEnvironment() {
        return environment;
    }

    /**
     * Sets the value of the environment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Runtimesetting }
     *     
     */
    public void setEnvironment(Runtimesetting value) {
        this.environment = value;
    }

    /**
     * Gets the value of the rulepacks property.
     * 
     * @return
     *     possible object is
     *     {@link RulePackList }
     *     
     */
    public RulePackList getRulepacks() {
        return rulepacks;
    }

    /**
     * Sets the value of the rulepacks property.
     * 
     * @param value
     *     allowed object is
     *     {@link RulePackList }
     *     
     */
    public void setRulepacks(RulePackList value) {
        this.rulepacks = value;
    }

    /**
     * Gets the value of the disabledRuleIds property.
     * 
     * @return
     *     possible object is
     *     {@link Runtimedisabledruleid }
     *     
     */
    public Runtimedisabledruleid getDisabledRuleIds() {
        return disabledRuleIds;
    }

    /**
     * Sets the value of the disabledRuleIds property.
     * 
     * @param value
     *     allowed object is
     *     {@link Runtimedisabledruleid }
     *     
     */
    public void setDisabledRuleIds(Runtimedisabledruleid value) {
        this.disabledRuleIds = value;
    }

}
