//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.08.06 at 10:51:02 PM IST 
//


package com.fortify.cli.aviator.fpr.jaxb;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SourceInstance" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;all&gt;
 *                   &lt;element ref="{xmlns://www.fortifysoftware.com/schema/fvdl}FunctionCall" minOccurs="0"/&gt;
 *                   &lt;element ref="{xmlns://www.fortifysoftware.com/schema/fvdl}FunctionEntry" minOccurs="0"/&gt;
 *                   &lt;element ref="{xmlns://www.fortifysoftware.com/schema/fvdl}SourceLocation" minOccurs="0"/&gt;
 *                   &lt;element ref="{xmlns://www.fortifysoftware.com/schema/fvdl}TaintFlags"/&gt;
 *                 &lt;/all&gt;
 *                 &lt;attribute name="ruleID" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sourceInstance"
})
@XmlRootElement(name = "Sources")
public class Sources {

    @XmlElement(name = "SourceInstance")
    protected List<Sources.SourceInstance> sourceInstance;

    /**
     * Gets the value of the sourceInstance property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the sourceInstance property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSourceInstance().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Sources.SourceInstance }
     * 
     * 
     */
    public List<Sources.SourceInstance> getSourceInstance() {
        if (sourceInstance == null) {
            sourceInstance = new ArrayList<Sources.SourceInstance>();
        }
        return this.sourceInstance;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;all&gt;
     *         &lt;element ref="{xmlns://www.fortifysoftware.com/schema/fvdl}FunctionCall" minOccurs="0"/&gt;
     *         &lt;element ref="{xmlns://www.fortifysoftware.com/schema/fvdl}FunctionEntry" minOccurs="0"/&gt;
     *         &lt;element ref="{xmlns://www.fortifysoftware.com/schema/fvdl}SourceLocation" minOccurs="0"/&gt;
     *         &lt;element ref="{xmlns://www.fortifysoftware.com/schema/fvdl}TaintFlags"/&gt;
     *       &lt;/all&gt;
     *       &lt;attribute name="ruleID" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class SourceInstance {

        @XmlElement(name = "FunctionCall")
        protected FunctionCall functionCall;
        @XmlElement(name = "FunctionEntry")
        protected FunctionEntry functionEntry;
        @XmlElement(name = "SourceLocation")
        protected SourceLocationType sourceLocation;
        @XmlElement(name = "TaintFlags", required = true)
        protected TaintFlags taintFlags;
        @XmlAttribute(name = "ruleID")
        protected String ruleID;

        /**
         * Gets the value of the functionCall property.
         * 
         * @return
         *     possible object is
         *     {@link FunctionCall }
         *     
         */
        public FunctionCall getFunctionCall() {
            return functionCall;
        }

        /**
         * Sets the value of the functionCall property.
         * 
         * @param value
         *     allowed object is
         *     {@link FunctionCall }
         *     
         */
        public void setFunctionCall(FunctionCall value) {
            this.functionCall = value;
        }

        /**
         * Gets the value of the functionEntry property.
         * 
         * @return
         *     possible object is
         *     {@link FunctionEntry }
         *     
         */
        public FunctionEntry getFunctionEntry() {
            return functionEntry;
        }

        /**
         * Sets the value of the functionEntry property.
         * 
         * @param value
         *     allowed object is
         *     {@link FunctionEntry }
         *     
         */
        public void setFunctionEntry(FunctionEntry value) {
            this.functionEntry = value;
        }

        /**
         * Gets the value of the sourceLocation property.
         * 
         * @return
         *     possible object is
         *     {@link SourceLocationType }
         *     
         */
        public SourceLocationType getSourceLocation() {
            return sourceLocation;
        }

        /**
         * Sets the value of the sourceLocation property.
         * 
         * @param value
         *     allowed object is
         *     {@link SourceLocationType }
         *     
         */
        public void setSourceLocation(SourceLocationType value) {
            this.sourceLocation = value;
        }

        /**
         * Gets the value of the taintFlags property.
         * 
         * @return
         *     possible object is
         *     {@link TaintFlags }
         *     
         */
        public TaintFlags getTaintFlags() {
            return taintFlags;
        }

        /**
         * Sets the value of the taintFlags property.
         * 
         * @param value
         *     allowed object is
         *     {@link TaintFlags }
         *     
         */
        public void setTaintFlags(TaintFlags value) {
            this.taintFlags = value;
        }

        /**
         * Gets the value of the ruleID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRuleID() {
            return ruleID;
        }

        /**
         * Sets the value of the ruleID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRuleID(String value) {
            this.ruleID = value;
        }

    }

}
