//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.08.06 at 10:51:02 PM IST 
//


package com.fortify.cli.aviator.fpr.jaxb;
import java.util.ArrayList;
import java.util.List;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * A sequence of nodes, or descriptions of points in the source code.
 * 
 * <p>Java class for UnifiedTrace complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UnifiedTrace"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="Primary"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Entry" maxOccurs="unbounded"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;choice&gt;
 *                             &lt;element name="Node"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;extension base="{xmlns://www.fortifysoftware.com/schema/fvdl}UnifiedNode"&gt;
 *                                     &lt;attribute name="isDefault" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *                                   &lt;/extension&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="NodeRef" type="{xmlns://www.fortifysoftware.com/schema/fvdl}UnifiedNodeRef"/&gt;
 *                           &lt;/choice&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/all&gt;
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UnifiedTrace", propOrder = {

})
public class UnifiedTrace {

    @XmlElement(name = "Primary", required = true)
    protected UnifiedTrace.Primary primary;
    @XmlAttribute(name = "id")
    protected Integer id;

    /**
     * Gets the value of the primary property.
     * 
     * @return
     *     possible object is
     *     {@link UnifiedTrace.Primary }
     *     
     */
    public UnifiedTrace.Primary getPrimary() {
        return primary;
    }

    /**
     * Sets the value of the primary property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnifiedTrace.Primary }
     *     
     */
    public void setPrimary(UnifiedTrace.Primary value) {
        this.primary = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setId(Integer value) {
        this.id = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Entry" maxOccurs="unbounded"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;choice&gt;
     *                   &lt;element name="Node"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;extension base="{xmlns://www.fortifysoftware.com/schema/fvdl}UnifiedNode"&gt;
     *                           &lt;attribute name="isDefault" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
     *                         &lt;/extension&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="NodeRef" type="{xmlns://www.fortifysoftware.com/schema/fvdl}UnifiedNodeRef"/&gt;
     *                 &lt;/choice&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "entry"
    })
    public static class Primary {

        @XmlElement(name = "Entry", required = true)
        protected List<UnifiedTrace.Primary.Entry> entry;

        /**
         * Gets the value of the entry property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the entry property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEntry().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link UnifiedTrace.Primary.Entry }
         * 
         * 
         */
        public List<UnifiedTrace.Primary.Entry> getEntry() {
            if (entry == null) {
                entry = new ArrayList<UnifiedTrace.Primary.Entry>();
            }
            return this.entry;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;choice&gt;
         *         &lt;element name="Node"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;extension base="{xmlns://www.fortifysoftware.com/schema/fvdl}UnifiedNode"&gt;
         *                 &lt;attribute name="isDefault" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
         *               &lt;/extension&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="NodeRef" type="{xmlns://www.fortifysoftware.com/schema/fvdl}UnifiedNodeRef"/&gt;
         *       &lt;/choice&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "node",
            "nodeRef"
        })
        public static class Entry {

            @XmlElement(name = "Node")
            protected UnifiedTrace.Primary.Entry.Node node;
            @XmlElement(name = "NodeRef")
            protected UnifiedNodeRef nodeRef;

            /**
             * Gets the value of the node property.
             * 
             * @return
             *     possible object is
             *     {@link UnifiedTrace.Primary.Entry.Node }
             *     
             */
            public UnifiedTrace.Primary.Entry.Node getNode() {
                return node;
            }

            /**
             * Sets the value of the node property.
             * 
             * @param value
             *     allowed object is
             *     {@link UnifiedTrace.Primary.Entry.Node }
             *     
             */
            public void setNode(UnifiedTrace.Primary.Entry.Node value) {
                this.node = value;
            }

            /**
             * Gets the value of the nodeRef property.
             * 
             * @return
             *     possible object is
             *     {@link UnifiedNodeRef }
             *     
             */
            public UnifiedNodeRef getNodeRef() {
                return nodeRef;
            }

            /**
             * Sets the value of the nodeRef property.
             * 
             * @param value
             *     allowed object is
             *     {@link UnifiedNodeRef }
             *     
             */
            public void setNodeRef(UnifiedNodeRef value) {
                this.nodeRef = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;extension base="{xmlns://www.fortifysoftware.com/schema/fvdl}UnifiedNode"&gt;
             *       &lt;attribute name="isDefault" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
             *     &lt;/extension&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Node
                extends UnifiedNode
            {

                @XmlAttribute(name = "isDefault")
                protected Boolean isDefault;

                /**
                 * Gets the value of the isDefault property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Boolean }
                 *     
                 */
                public Boolean isIsDefault() {
                    return isDefault;
                }

                /**
                 * Sets the value of the isDefault property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Boolean }
                 *     
                 */
                public void setIsDefault(Boolean value) {
                    this.isDefault = value;
                }

            }

        }

    }

}
