name: Bump shared-github pin

on:
  schedule:
    - cron: '0 6 * * *'   # daily
  workflow_dispatch:
  push:

permissions:
  contents: read

jobs:
  bump:
    uses: fortify/shared-github/.github/workflows/reusable-bump-shared-pin.yml@32d62c22c636c1b185f297ed573e2caf2d53d33f
