name: Fortify on Demand Scan
run-name: "Fortify on Demand Scan (${{ github.event_name }})"

on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
    - cron: '16 0 * * 5'

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  check-duplicate-run:
    uses: fortify/shared-github/.github/workflows/reusable-check-duplicate-run.yml@f770891b6964394472880428517a4b5c7cd57740

  FoD-Scan:
    needs: check-duplicate-run
    if: needs.check-duplicate-run.outputs.should_skip != 'true'
    uses: fortify/shared-github/.github/workflows/reusable-fortify-analysis.yml@f770891b6964394472880428517a4b5c7cd57740
    with:
      java-version: '17'
    secrets: inherit
