name: update-repo-docs

on:
  workflow_dispatch:
  schedule:
    - cron: '5 4 * * *'
  push:
    branches:
      - dev/v3.x
      
jobs:
  update-repo-docs:
    permissions:
      contents: write
      pull-requests: write
    uses: fortify/shared-github/.github/workflows/reusable-update-repo-docs.yml@6660783b1acb464406106b3d2d4f45810fca41ee
