name: update-repo-docs

on:
  workflow_dispatch:
  schedule:
    - cron: '5 4 * * *'
  push:
    branches:
      - dev/v3.x
      
jobs:
  update-repo-docs:
    permissions:
      contents: write
    uses: fortify/shared-doc-resources/.github/workflows/update-repo-docs.yml@main