name: update-repo-docs

on:
  workflow_dispatch:
  schedule:
    - cron: '5 4 * * *'
  push:
    branches:
      - dev/v3.x
      
jobs:
  update-repo-docs:
    permissions:
      contents: write
      pull-requests: write
    uses: fortify/shared-github/.github/workflows/reusable-update-repo-docs.yml@f770891b6964394472880428517a4b5c7cd57740
